export default function Paper2Page() {
  const trapSections = [
    {
      title: "Constitutional Articles",
      items: [
        "CAG → Article 148",
        "Finance Commission → Article 280",
        "Election Commission → Article 324",
        "NCSC → Article 338",
        "86th Amendment → Article 21A + Article 45 + Fundamental Duty of parents",
      ],
    },
    {
      title: "Political Thinkers",
      items: [
        "Locke → Labour Theory of Property",
        "Lenin → Vanguard Party",
        "Gandhi → Bread Labour",
        "Weber → Caste analysis in Indian society",
        "Lohia → Four-Pillar State",
      ],
    },
    {
      title: "Chronology Traps",
      items: [
        "Golaknath → Minerva Mills → Indra Sawhney → Puttaswamy → Navtej Johar",
        "Look East Policy → Gujral Doctrine → Pokhran-II → Lahore Bus Diplomacy",
        "Portugal 1974 → Spain 1975 → Berlin Wall 1989 → South Africa 1994",
        "UNESCO 1945 → UNICEF 1946 → WHO 1948 → UNEP 1972",
      ],
    },
    {
      title: "Indian Polity Traps",
      items: [
        "NOTA → PUCL v. Union of India",
        "Ambedkar resigned partly due to delay of Hindu Code Bill",
        "Sixth Schedule states → Assam, Meghalaya, Mizoram, Tripura",
        "Manipur is NOT under Sixth Schedule",
        "CAG is accountable to Parliament",
      ],
    },
    {
      title: "IR Traps",
      items: [
        "SAARC members → India, Pakistan, Bangladesh, Nepal, Bhutan, Sri Lanka, Maldives, Afghanistan",
        "Mauritius is NOT a SAARC member",
        "Newest UN member → South Sudan",
        "US Executive Power → Article II",
        "First armed UN peacekeeping force → UNEF-I, Suez Crisis, 1956",
      ],
    },
    {
      title: "Public Administration",
      items: [
        "Fayol → Control is NOT one of 14 principles",
        "Taylor → Science, harmony, cooperation, maximum output",
        "Amitai Etzioni → Coercive, Utilitarian, Normative organizations",
        "Sarkaria Commission → Centre-State Relations",
        "Organizational Myopia → Agency interest over public interest",
      ],
    },
  {
  title: "Thinkers and Concepts",
  items: [
    "Hobbes → Absolute sovereign, no right to rebellion",
    "Locke → Natural rights + right to rebellion",
    "Rousseau → General Will",
    "Trotsky → Permanent Revolution",
    "Stalin → Socialism in One Country",
    "Juan Linz → Presidentialism vs Parliamentarism",
    "Amitai Etzioni → Coercive, Utilitarian, Normative organizations",
    "M.N. Roy → New Humanism",
    "Tagore → Nationalism",
    "Lohia → Four-Pillar State",
  ],
},
  {
  title: "Chronology War Room",
  items: [
    "Fundamental Rights cases → Golaknath 1967 → Minerva Mills 1980 → Indra Sawhney 1992 → Puttaswamy 2017 → Navtej Johar 2018",
    "Indian Foreign Policy → Look East 1991 → Gujral Doctrine 1996–97 → Pokhran-II 1998 → Lahore Bus Diplomacy 1999",
    "Democratization → Portugal 1974 → Spain 1975 → Berlin Wall 1989 → South Africa 1994",
    "UN bodies → UNESCO 1945 → UNICEF 1946 → WHO 1948 → UNEP 1972",
    "Public Administration → Development Administration 1950s → Comparative Administration Group (CAG) 1960 → Minnowbrook 1968 → NPM 1991",
    "Regional Organizations → Council of Europe 1949 → Nordic Council 1952 → EFTA 1960 → OECD 1961",
    "CAG chronology → A.K. Chanda → V.N. Kaul → Vinod Rai → G.C. Murmu → K. Sanjay Murthy (current, since Nov 2024)",
    "Political Thought → Aggannasutta → Tagore → M.N. Roy → Lohia",
  ],
},
{
  title: "Constitution and Polity Traps",
  items: [
    "CAG → Article 148",
    "Finance Commission → Article 280",
    "Election Commission → Article 324",
    "NCSC → Article 338",
    "86th Amendment → Article 21A inserted",
    "86th Amendment → Article 45 modified",
    "86th Amendment → Fundamental Duty added for parents",
    "NOTA → PUCL v. Union of India (2013)",
    "Ambedkar resigned partly due to delay of Hindu Code Bill",
    "Sixth Schedule → Assam, Meghalaya, Mizoram, Tripura",
    "Manipur is NOT a Sixth Schedule state",
    "PESA → Chairperson at all levels reserved for STs",
    "CAG accountable to Parliament",
    "US Executive Power → Article II",
    "Newest UN Member → South Sudan (2011)",
  ],
},
{
  title: "IR and International Organizations War Room",
  items: [
    "SAARC Members → India, Pakistan, Bangladesh, Nepal, Bhutan, Sri Lanka, Maldives, Afghanistan",
    "Mauritius is NOT a SAARC member",
    "NAM → Countries should not be tied to Cold War military blocs",
    "UNEF-I → First armed UN Peacekeeping Force (Suez Crisis, 1956)",
    "UNESCO → 1945",
    "UNICEF → 1946",
    "WHO → 1948",
    "UNEP → 1972",
    "South Sudan → Newest UN Member (2011)",
    "Nordic Council → 1952",
    "Council of Europe → 1949",
    "EFTA → 1960",
    "OECD → 1961",
    "Look East Policy → 1991",
    "Gujral Doctrine → 1996–97",
    "Pokhran-II → 1998",
    "Lahore Bus Diplomacy → 1999",
    "Panchamrit Goal → Net Zero by 2070",
  ],
},
{
  title: "Public Administration Rapid Revision",
  items: [
    "Fayol → Control is NOT among the 14 Principles",
    "Taylor → Science, not Rule of Thumb",
    "Taylor → Harmony, not Discord",
    "Taylor → Cooperation, not Individualism",
    "Taylor → Maximum Output",
    "Etzioni → Coercive, Utilitarian, Normative Organizations",
    "Organizational Myopia → Agency interest over public interest",
    "Sarkaria Commission → Centre-State Relations",
    "Development Administration → 1950s",
    "Minnowbrook Conference → 1968",
    "Christopher Hood → New Public Management (1991)",
    "Elton Mayo → Human Problems → Social Problems → Political Problems",
  ],
},
{
  title: "Research Methodology War Room",
  items: [
    "Ecological Validity → Generalization to real-world settings",
    "Action Research → Solves local problems, context-specific",
    "Standard Deviation → Uses all scores and squared deviations",
    "Parametric Tests → Assume population parameters",
    "Non-Parametric Tests → No population assumption required",
    "Plagiarism → Using others' work without acknowledgment",
    "Predatory Journals → Charge fees without proper peer review",
    "Clone Journals → Fake websites mimicking genuine journals",
    "Publish or Perish → Pressure to publish for career advancement",
    "Academic Integrity → Honesty, transparency, originality",
    "Criterion Referenced Test → Measures performance against standards",
    "Cross Sectional Research → Data collected at one point in time",
  ],
},
{
  title: "Teaching Aptitude War Room",
  items: [
    "Metacognition → Thinking about one's own thinking",
    "Bloom Revised Taxonomy → Remember, Understand, Apply, Analyze, Evaluate, Create",
    "Kounin → Withitness",
    "Donald Schon → Reflective Teaching",
    "Delors Report → Learning to Know, Do, Live Together, Be",
    "Affective Domain Highest Level → Characterization",
    "Psychomotor Domain → Skill-based learning",
    "Reflective Teacher → Continuously evaluates own teaching",
    "Learner-Centered Teaching → Focus on student learning process",
    "Professional Ethics → Integrity, fairness, accountability",
  ],
},
{
  title: "ICT War Room",
  items: [
    "Charles Babbage → Analytical Engine",
    "Ada Lovelace → First Computer Programmer",
    "Alan Turing → Father of Modern Theoretical Computer Science",
    "Tim Berners-Lee → Inventor of World Wide Web",
    "Deep Web → Not indexed by search engines",
    "Dark Web → Small encrypted part of Deep Web",
    "Narrow AI → Designed for specific tasks",
    "Self-Aware AI → Does not currently exist",
    "WWW → Invented by Tim Berners-Lee",
    "Analytical Engine → Charles Babbage",
    "Cyber Hygiene → Safe online practices",
    "Two-Factor Authentication → Extra security layer",
  ],
},
{
  title: "Communication War Room",
  items: [
    "Parasocial Interaction → One-sided relationship with media personalities",
    "Written Communication → Verbal communication",
    "Body Language → Non-verbal communication",
    "Facial Expression → Non-verbal communication",
    "Gestures → Non-verbal communication",
    "Non-verbal cues are difficult to control",
    "Communication Channel → Medium through which message travels",
    "Latency → Delay in communication process",
    "Feedback → Response from receiver",
    "Noise → Interference in communication",
    "Semantic Noise → Misinterpretation of words",
    "Mass Communication → One-to-many communication",
  ],
},
{
  title: "Environment War Room",
  items: [
    "DDT → Biomagnification",
    "Excess Fluoride → Fluorosis",
    "Low Fluoride → Dental caries (optimal fluoride prevents caries)",
    "E-Waste Rules → 2016, replaced by E-Waste (Management) Rules 2022",
    "Construction & Demolition Waste Rules → 2016",
    "Mission LiFE → Lifestyle for Environment",
    "Panchamrit → India's climate commitments",
    "Net Zero Target → 2070",
    "Leachate → Liquid formed from waste decomposition",
    "Biodiversity Hotspot → High endemic species and threat",
    "Carbon Sink → Absorbs more carbon than releases",
    "Sustainable Development → Meet present needs without harming future generations",
  ],
},
{
  title: "Exam Hall Kill-Shots",
  items: [
    "CAG → Article 148",
    "Finance Commission → Article 280",
    "Election Commission → Article 324",
    "NCSC → Article 338",
    "Locke → Labour Theory of Property",
    "Lenin → Vanguard Party",
    "Gandhi → Bread Labour",
    "Weber → Caste analysis",
    "Fayol → Control NOT among 14 Principles",
    "Taylor → Science, Harmony, Cooperation",
    "NOTA → PUCL v. Union of India",
    "Ambedkar → Hindu Code Bill controversy",
    "Mauritius → NOT a SAARC member",
    "South Sudan → Newest UN Member",
    "UNEF-I → First armed UN Peacekeeping Force",
    "Manipur → NOT under Sixth Schedule",
    "Article II (US Constitution) → Executive Power",
    "Sarkaria Commission → Centre-State Relations",
    "Etzioni → Coercive, Utilitarian, Normative Organizations",
    "Juan Linz → Presidentialism vs Parliamentarism",
  ],
},
{
  title: "Research Ethics Kill-Shots",
  items: [
    "Plagiarism → Use of others' work without acknowledgment",
    "Self-Plagiarism → Reusing one's own published work without disclosure",
    "Fabrication → Making up data",
    "Falsification → Manipulating data",
    "FFP → Fabrication, Falsification, Plagiarism",
    "Predatory Journal → Charges fees without proper peer review",
    "Clone Journal → Fake copy of a genuine journal",
    "Peer Review → Evaluation by experts before publication",
    "Impact Factor → Citation-based journal metric",
    "Publish or Perish → Academic pressure to publish",
    "Academic Integrity → Honesty and originality",
    "Retraction → Withdrawal of published article",
  ],
},
{
  title: "Committees, Commissions and Reports",
  items: [
    "Sarkaria Commission → Centre-State Relations",
    "Punchhi Commission → Centre-State Relations Review",
    "Dantwala Committee (1978) → Block-Level Planning",
    "Hanumantha Rao Committee (1984) → District Planning",
    "GVK Rao Committee (1985) → Administrative Arrangements for Rural Development",
    "L.M. Singhvi Committee (1986) → Constitutional recognition of Panchayati Raj",
    "Thungon Committee (1988) → Constitutional Status to Panchayats",
    "Balwant Rai Mehta Committee (1957) → Democratic Decentralization, three-tier PRI",
    "Ashok Mehta Committee (1977-78) → Two-Tier Panchayati Raj",
    "Administrative Reforms Commission → Public Administration Reforms",
    "Narasimham Committee → Banking Reforms",
    "Nanavati Commission → 1984 anti-Sikh riots | Nanavati-Mehta Commission → 2002 Gujarat riots",
  ],
},
{
  title: "Constitutional Cases War Room",
  items: [
    "Shankari Prasad (1951) → Parliament can amend Fundamental Rights",
    "Golaknath (1967) → Parliament cannot amend Fundamental Rights",
    "Kesavananda Bharati (1973) → Basic Structure Doctrine",
    "Minerva Mills (1980) → Limited Amending Power",
    "Indra Sawhney (1992) → Reservation Case",
    "Puttaswamy (2017) → Right to Privacy",
    "Navtej Johar (2018) → Section 377 struck down",
    "PUCL (2013) → NOTA",
    "Basic Structure → Cannot be destroyed by amendment",
    "Preamble → Part of Constitution (Kesavananda Bharati)",
  ],
},
{
  title: "Political Science One-Liners",
  items: [
    "Behavioralism → Scientific study of political behaviour",
    "Post-Behavioralism → Relevance and action",
    "Political Culture → Almond and Verba",
    "General Will → Rousseau",
    "Permanent Revolution → Trotsky",
    "Socialism in One Country → Stalin",
    "New Humanism → M.N. Roy",
    "Four-Pillar State → Ram Manohar Lohia",
    "Nationalism → Rabindranath Tagore",
    "Caste Analysis → Max Weber",
    "Presidentialism vs Parliamentarism → Juan Linz",
    "Organizational Typology → Amitai Etzioni",
  ],
},
{
  title: "SUPER CHRONOLOGY WAR ROOM",
  items: [
    "Shankari Prasad 1951 → Golaknath 1967 → Kesavananda Bharati 1973 → Minerva Mills 1980 → Indra Sawhney 1992 → Puttaswamy 2017 → Navtej Johar 2018",
    "Portugal 1974 → Spain 1975 → Berlin Wall 1989 → South Africa 1994",
    "Look East Policy 1991 → Gujral Doctrine 1996–97 → Pokhran-II 1998 → Lahore Bus Diplomacy 1999",
    "UNESCO 1945 → UNICEF 1946 → WHO 1948 → UNEP 1972",
    "Council of Europe 1949 → Nordic Council 1952 → EFTA 1960 → OECD 1961",
    "Development Administration 1950s → Comparative Administration Group 1960 → Minnowbrook 1968 → NPM 1991",
    "Aggannasutta → Tagore → M.N. Roy → Lohia",
    "Dantwala 1978 → Hanumantha Rao 1984 → GVK Rao 1985 → L.M. Singhvi 1986 → Thungon 1988",
    "A.K. Chanda → V.N. Kaul → Vinod Rai → G.C. Murmu",
    "Girl Child 1990 → Disabled Persons 1991 → Environment 1992 → Poverty Eradication 1995 → Youth 1996",
  ],
},
{
  title: "UGC NET Statement Traps",
  items: [
    "Read ALL statements before looking at options",
    "One wrong word can make the entire statement false",
    "Always verify chronology questions twice",
    "NTA often places two correct statements beside one incorrect statement",
    "Articles and Constitutional Bodies are frequent trap areas",
    "Thinkers are often asked through concepts, not direct names",
    "IR questions increasingly combine current affairs with theory",
    "Assertion-Reason questions often contain two true statements",
    "If both A and R are true, check whether R actually explains A",
    "Committee questions often test chronology rather than functions",
    "Mock tests overemphasize facts; NTA increasingly tests application",
    "Political Theory questions often hide thinker names",
  ],
},
{
  title: "Constitutional Amendments War Room",
  items: [
    "1st Amendment 1951 → Added reasonable restrictions to freedom of speech",
    "7th Amendment 1956 → Reorganization of states",
    "42nd Amendment 1976 → Mini Constitution",
    "42nd Amendment → Added Socialist, Secular, Integrity to Preamble",
    "44th Amendment 1978 → Right to Property removed from Fundamental Rights",
    "52nd Amendment 1985 → Anti-Defection Law",
    "61st Amendment 1988 → Voting age reduced from 21 to 18",
    "73rd Amendment 1992 → Panchayati Raj",
    "74th Amendment 1992 → Municipalities",
    "86th Amendment 2002 → Right to Education",
    "91st Amendment 2003 → Limited size of Council of Ministers",
    "101st Amendment 2016 → GST",
    "103rd Amendment 2019 → EWS reservation",
    "106th Amendment 2023 → Women reservation in Lok Sabha and State Assemblies",
  ],
},
{
  title: "Higher Education and NEP War Room",
  items: [
    "NEP 2020 → Multidisciplinary education",
    "NEP 2020 → Multiple entry and exit system",
    "NEP 2020 → Academic Bank of Credit",
    "ABC → Academic Bank of Credit",
    "NCrF → National Credit Framework",
    "SWAYAM → Indian platform for MOOCs",
    "MOOC → Massive Open Online Course",
    "Radhakrishnan Commission → University Education",
    "Mudaliar Commission → Secondary Education",
    "Kothari Commission → Education and National Development",
    "National Knowledge Commission → Knowledge-based development",
    "Open and Distance Learning → Flexible learner-centered education",
  ],
},
{
  title: "Political Theory Kill-Shots",
  items: [
    "Plato → Philosopher King",
    "Plato → Theory of Justice",
    "Aristotle → Classification of Constitutions",
    "Aristotle → Man is a Political Animal",
    "Machiavelli → Reason of State",
    "Hobbes → Leviathan",
    "Hobbes → No Right to Rebellion",
    "Locke → Natural Rights",
    "Locke → Consent of the Governed",
    "Rousseau → General Will",
    "Bentham → Utilitarianism",
    "J.S. Mill → Liberty",
    "Hegel → Dialectics",
    "Marx → Historical Materialism",
    "Gramsci → Cultural Hegemony",
    "Rawls → Veil of Ignorance",
    "Nozick → Minimal State",
    "Isaiah Berlin → Positive and Negative Liberty",
  ],
},
{
  title: "Indian Political Thought",
  items: [
    "Kautilya → Arthashastra",
    "Kautilya → Saptanga Theory",
    "M.N. Roy → New Humanism",
    "Gandhi → Sarvodaya",
    "Gandhi → Bread Labour",
    "Ambedkar → Annihilation of Caste",
    "Ambedkar → Hindu Code Bill",
    "Nehru → Democratic Socialism",
    "Lohia → Four-Pillar State",
    "Tagore → Critique of Aggressive Nationalism",
    "Savarkar → Hindutva",
    "Aurobindo → Spiritual Nationalism",
    "Jayaprakash Narayan → Total Revolution",
  ],
},
{
  title: "Comparative Politics War Room",
  items: [
    "Gabriel Almond → Structural Functionalism",
    "Almond and Verba → Civic Culture",
    "David Easton → Systems Theory",
    "Karl Deutsch → Communication Theory",
    "Samuel Huntington → Political Order in Changing Societies",
    "Juan Linz → Presidentialism vs Parliamentarism",
    "Arend Lijphart → Consensus Democracy",
    "Maurice Duverger → Duverger's Law",
    "Political Development → Differentiation and Capacity Building",
    "Political Modernization → Shift from Traditional to Modern Politics",
    "Political Culture → Attitudes and Orientations towards Politics",
    "Civic Culture → Participant + Subject + Parochial Mix",
    "Developed Countries → High Institutionalization",
    "Developing Countries → Nation-Building and State-Building Challenges",
  ],
},
{
  title: "Political Sociology War Room",
  items: [
    "Political Socialization → Learning Political Values",
    "Family → Primary Agent of Political Socialization",
    "Media → Major Agent of Political Socialization",
    "Political Culture → Almond and Verba",
    "Elite Theory → Pareto, Mosca, Michels",
    "Iron Law of Oligarchy → Robert Michels",
    "Circulation of Elites → Vilfredo Pareto",
    "Power Elite → C. Wright Mills",
    "Class Struggle → Karl Marx",
    "Status Groups → Max Weber",
    "Caste Analysis → Max Weber",
    "Dominant Caste → M.N. Srinivas",
    "Sanskritization → M.N. Srinivas",
    "Westernization → M.N. Srinivas",
  ],
},
{
  title: "One-Liner Trap Notes",
  items: [
    "Mauritius → NOT SAARC",
    "South Sudan → Newest UN Member",
    "Manipur → NOT Sixth Schedule",
    "Control → NOT Fayol's 14 Principles",
    "Locke → Right to Rebellion",
    "Hobbes → No Right to Rebellion",
    "Article 148 → CAG",
    "Article 280 → Finance Commission",
    "Article 324 → Election Commission",
    "Article 338 → NCSC",
    "NOTA → PUCL",
    "Ambedkar → Hindu Code Bill",
    "Lenin → Vanguard Party",
    "Gandhi → Bread Labour",
    "Etzioni → Organizational Typology",
  ],
},
{
  title: "International Relations Theory War Room",
  items: [
    "Classical Realism → Hans Morgenthau",
    "Neorealism → Kenneth Waltz",
    "Offensive Realism → John Mearsheimer",
    "Liberalism → Cooperation among states possible",
    "Neoliberal Institutionalism → Robert Keohane",
    "Constructivism → Alexander Wendt",
    "Wendt → Anarchy is what states make of it",
    "English School → Hedley Bull",
    "Dependency Theory → Andre Gunder Frank",
    "World Systems Theory → Immanuel Wallerstein",
    "Clash of Civilizations → Samuel Huntington",
    "End of History → Francis Fukuyama",
    "Balance of Power → Realist concept",
    "Collective Security → Liberal concept",
    "Security Dilemma → Realist concept",
    "Soft Power → Joseph Nye",
    "Hard Power → Military and Economic Coercion",
    "Smart Power → Combination of Hard and Soft Power",
  ],
},
{
  title: "IR Comparison Kill-Shots",
  items: [
    "Morgenthau vs Waltz → Classical Realism vs Neorealism",
    "Rawls vs Nozick → Welfare State vs Minimal State",
    "Marx vs Weber → Class vs Multi-dimensional Stratification",
    "Plato vs Aristotle → Ideal State vs Practical State",
    "Hobbes vs Locke → Absolute Sovereign vs Limited Government",
    "Locke vs Rousseau → Liberalism vs Popular Sovereignty",
    "Bentham vs Mill → Quantitative vs Qualitative Utilitarianism",
    "Realism vs Liberalism → Conflict vs Cooperation",
    "Realism vs Constructivism → Material Power vs Ideas",
    "Presidential vs Parliamentary → Separation vs Fusion of Powers",
    "Unitary vs Federal → Centralization vs Constitutional Division of Powers",
  ],
},
{
  title: "Last Night Before Exam",
  items: [
    "CAG → 148",
    "Finance Commission → 280",
    "Election Commission → 324",
    "NCSC → 338",
    "NOTA → PUCL",
    "Locke → Labour Theory + Right to Rebellion",
    "Hobbes → No Right to Rebellion",
    "Lenin → Vanguard Party",
    "Gandhi → Bread Labour",
    "Lohia → Four-Pillar State",
    "M.N. Roy → New Humanism",
    "South Sudan → Newest UN Member",
    "Mauritius → NOT SAARC",
    "Manipur → NOT Sixth Schedule",
    "Control → NOT Fayol Principle",
    "Wendt → Anarchy is what states make of it",
    "Keohane → Neoliberal Institutionalism",
    "Waltz → Neorealism",
    "Morgenthau → Classical Realism",
    "Rawls → Veil of Ignorance",
  ],
},
{
  title: "Fallacy War Room",
  items: [
    "Ad Hominem → Attack person, not argument",
    "Straw Man → Misrepresent opponent's argument",
    "Hasty Generalization → Small sample, broad conclusion",
    "False Cause → Correlation assumed as causation",
    "Bandwagon → Popularity equals truth",
    "Appeal to Authority → Expert opinion treated as proof",
    "Circular Reasoning → Conclusion used as evidence",
    "Slippery Slope → Extreme consequences assumed",
    "False Dilemma → Only two choices presented",
    "Red Herring → Irrelevant issue introduced",
    "Tu Quoque → 'You also do it' response",
    "Appeal to Emotion → Emotion replaces evidence",
  ],
},
{
  title: "Alphabet Coding War Room",
  items: [
    "A=1 B=2 C=3 ... Z=26",
    "Position of M = 13",
    "Position of Z = 26",
    "Reverse Position: A=26, B=25, C=24 ... Z=1",
    "Opposite Letters → A-Z, B-Y, C-X, D-W",
    "CAT → 3+1+20 = 24",
    "DOG → 4+15+7 = 26",
    "MANGO → 13+1+14+7+15 = 50",
    "Check difference between letters first",
    "Most coding questions use position patterns",
  ],
},
{
  title: "Series Recognition War Room",
  items: [
    "2,4,6,8 → +2 pattern",
    "3,6,12,24 → ×2 pattern",
    "1,4,9,16 → Squares",
    "1,8,27,64 → Cubes",
    "2,3,5,7,11 → Prime Numbers",
    "Alternate series are common in UGC NET",
    "Check difference first",
    "Check multiplication second",
    "Check square/cube pattern third",
    "Odd-even position patterns are frequent",
  ],
},
{
  title: "Math Survival Guide: Average",
  items: [
    "Question: Average of 5 numbers is 20. Find total.",
    "Think: Average = Total ÷ Number",
    "Reverse it: Total = Average × Number",
    "20 × 5 = 100",
    "Answer = 100",
    "Shortcut: If average and number are given, multiply immediately.",
  ],
},
{
  title: "Math Survival Guide: Percentage",
  items: [
    "Question: What is 25% of 400?",
    "Think: 25% = 1/4",
    "400 ÷ 4 = 100",
    "Answer = 100",
    "Shortcut: 10%=÷10, 25%=÷4, 50%=÷2, 75%=3/4",
  ],
},
{
  title: "Math Survival Guide: Profit and Loss",
  items: [
    "Question: CP=100, SP=120. Find Profit%.",
    "Think: Profit = SP - CP",
    "Profit = 120 - 100 = 20",
    "Profit% = 20 ÷ 100 × 100",
    "Answer = 20%",
    "Shortcut: If CP=100, SP itself shows profit/loss percentage.",
  ],
},
{
  title: "Math Survival Guide: Ratio",
  items: [
    "Question: Ratio 2:3, Total=500.",
    "Think: Total parts = 2+3 = 5",
    "One part = 500 ÷ 5 = 100",
    "A = 2×100 = 200",
    "B = 3×100 = 300",
    "Shortcut: Add ratio parts first.",
  ],
},
{
  title: "Math Survival Guide: Probability",
  items: [
    "Question: Probability of getting an even number on a die.",
    "Think: Favorable ÷ Total",
    "Even numbers = 2,4,6",
    "Favorable = 3",
    "Total = 6",
    "Answer = 3/6 = 1/2",
    "Shortcut: Even numbers on die always = 1/2",
  ],
},
{
  title: "Data Interpretation Survival Guide",
  items: [
    "Question: Which year has the highest value?",
    "Think: Find tallest bar or biggest number.",
    "Answer: Highest value is always the tallest bar.",
    "Shortcut: Do not calculate anything.",

    "Question: Which year has the lowest value?",
    "Think: Find shortest bar or smallest number.",
    "Answer: Lowest value is always the shortest bar.",
    "Shortcut: Usually 5-second question.",

    "Question: Find difference between 2021 and 2023.",
    "Think: Bigger value - Smaller value.",
    "Example: 250 - 150 = 100",
    "Answer = 100",

    "Question: Find average.",
    "Think: Add all values then divide by number of years.",
    "Example: 100+150+200+250=700",
    "700 ÷ 4 = 175",
    "Answer = 175",

    "Question: Percentage increase.",
    "Formula: (New - Old) ÷ Old × 100",
    "Example: 100 → 200",
    "Increase = 100",
    "100 ÷ 100 × 100 = 100%",
    "Answer = 100%",
  ],
},
{
  title: "Percentage Increase Shortcut",
  items: [
    "100 → 200 = 100% increase",
    "100 → 300 = 200% increase",
    "100 → 400 = 300% increase",
    "100 → 150 = 50% increase",
    "100 → 125 = 25% increase",
    "100 → 50 = 50% decrease",
    "100 → 75 = 25% decrease",
    "Double = 100% increase",
    "Triple = 200% increase",
    "Half = 50% decrease",
  ],
},
{
  title: "Mean Median Mode Survival Guide",
  items: [
    "Mean = Average",
    "Mean = Sum ÷ Number",

    "Question: Find mean of 10,20,30",
    "10+20+30=60",
    "60÷3=20",
    "Answer = 20",

    "Median = Middle value after arranging",
    "10,20,30,40,50",
    "Middle = 30",
    "Answer = 30",

    "Mode = Most repeated value",
    "10,20,20,30",
    "20 repeats most",
    "Answer = 20",

    "Shortcut: Mean=Average, Median=Middle, Mode=Most",
  ],
},
{
  title: "Standard Deviation Survival Guide",
  items: [
    "Purpose: Measures spread of data",
    "Small SD = Values close together",
    "Large SD = Values far apart",
    "UGC NET usually asks concept, not full calculation",
    "If all values are same → SD = 0",
    "Higher spread = Higher SD",
    "Lower spread = Lower SD",
    "Remember: SD measures variability",
  ],
},
{
  title: "Research Methodology Statistics War Room",
  items: [
    "Reliability = Consistency of measurement",
    "Validity = Measuring what is intended",
    "High Reliability ≠ High Validity",
    "High Validity usually requires Reliability",

    "Sampling = Selecting part of population",
    "Population = Entire group under study",
    "Sample = Subset of population",

    "Simple Random Sampling = Equal chance for everyone",
    "Stratified Sampling = Population divided into strata",
    "Cluster Sampling = Whole clusters randomly selected; everyone in chosen clusters studied",
    "Purposive Sampling = Researcher selects participants",

    "Null Hypothesis (H0) = No relationship/no difference",
    "Alternative Hypothesis (H1) = Relationship/difference exists",

    "Type I Error = Rejecting true H0",
    "Type II Error = Failing to reject (accepting) a false H0",

    "Positive Correlation = Both increase together",
    "Negative Correlation = One increases, one decreases",
    "Zero Correlation = No relationship",

    "Correlation ≠ Causation",
  ],
},
{
  title: "Research Methodology Kill-Shots",
  items: [
    "Ecological Validity = Real-world applicability",
    "Internal Validity = Control of variables",
    "External Validity = Generalizability",
    "Action Research = Solving local practical problems",
    "Cross-Sectional Study = One point in time",
    "Longitudinal Study = Multiple time periods",
    "Pilot Study = Small-scale preliminary study",
    "Case Study = In-depth examination of one case",
    "Variable = Characteristic that changes",
    "Independent Variable = Cause",
    "Dependent Variable = Effect",
    "Research Design = Blueprint of study",
  ],
},
{
  title: "Higher Education and Commissions Master Sheet",
  items: [
    "Radhakrishnan Commission (1948-49) → University Education",
    "Mudaliar Commission (1952-53) → Secondary Education",
    "Kothari Commission (1964-66) → Education and National Development",
    "National Knowledge Commission → Knowledge Society",
    "NEP 2020 → Multidisciplinary Education",
    "NEP 2020 → Multiple Entry and Exit",
    "NEP 2020 → Academic Bank of Credits",
    "ABC → Academic Bank of Credits",
    "SWAYAM → MOOCs Platform",
    "MOOC → Massive Open Online Course",
    "NAAC → Quality Assessment and Accreditation",
    "NIRF → Ranking of Higher Education Institutions",
    "UGC → Coordination and Maintenance of Standards",
    "ICSSR → Social Science Research",
    "ICHR → Historical Research",
    "ICPR → Philosophical Research",
    "NCTE → Teacher Education",
    "AICTE → Technical Education",
  ],
},
{
  title: "Teaching Aptitude Master Sheet",
  items: [
    "Bloom Revised Taxonomy → Remember, Understand, Apply, Analyze, Evaluate, Create",
    "Metacognition → Thinking about Thinking",
    "Kounin → Withitness",
    "Donald Schon → Reflective Practitioner",
    "Delors Report → Learning to Know",
    "Delors Report → Learning to Do",
    "Delors Report → Learning to Live Together",
    "Delors Report → Learning to Be",
    "Affective Domain Highest Level → Characterization",
    "Psychomotor Domain → Skill Development",
    "Learner-Centered Teaching → Student Focused",
    "Teacher-Centered Teaching → Teacher Focused",
    "Formative Evaluation → During Learning",
    "Summative Evaluation → End of Learning",
  ],
},
{
  title: "Communication Master Sheet",
  items: [
    "Sender → Message → Channel → Receiver → Feedback",
    "Noise → Interference in Communication",
    "Semantic Noise → Meaning Distortion",
    "Feedback → Response from Receiver",
    "Body Language → Non-Verbal Communication",
    "Facial Expression → Non-Verbal Communication",
    "Gesture → Non-Verbal Communication",
    "Mass Communication → One to Many",
    "Interpersonal Communication → One to One",
    "Parasocial Interaction → One-sided Media Relationship",
    "Latency → Delay in Communication",
    "Communication Channel → Medium of Message",
  ],
},
{
  title: "Environment and Ecology Master Sheet",
  items: [
    "DDT → Biomagnification",
    "Fluorosis → Excess Fluoride",
    "Dental Caries Prevention → Appropriate Fluoride",
    "Leachate → Liquid from Waste Decomposition",
    "Carbon Sink → Absorbs More Carbon than Releases",
    "Biodiversity Hotspot → High Endemism + High Threat",
    "Mission LiFE → Lifestyle for Environment",
    "Panchamrit → India's COP26 Climate Commitments",
    "Net Zero Target → 2070",
    "E-Waste Management Rules → 2016, replaced by 2022 Rules",
    "Construction and Demolition Waste Rules → 2016",
    "Ozone Layer → Absorbs UV Radiation",
    "Montreal Protocol → Ozone Protection",
    "Kyoto Protocol → Greenhouse Gas Reduction",
    "Paris Agreement → Climate Change Mitigation",
    "Sustainable Development → Present Needs without harming Future Generations",
  ],
},
{
  title: "ICT Master Sheet",
  items: [
    "Charles Babbage → Analytical Engine",
    "Ada Lovelace → First Programmer",
    "Alan Turing → Father of Theoretical Computer Science and AI (Babbage = Father of the Computer)",
    "Tim Berners-Lee → World Wide Web",
    "WWW → World Wide Web",
    "URL → Uniform Resource Locator",
    "HTTP → HyperText Transfer Protocol",
    "HTTPS → Secure HTTP",
    "Deep Web → Not Indexed by Search Engines",
    "Dark Web → Encrypted Part of Deep Web",
    "AI → Artificial Intelligence",
    "Narrow AI → Task-Specific Intelligence",
    "Machine Learning → Learning from Data",
    "Cyber Hygiene → Safe Online Practices",
    "Two Factor Authentication → Additional Security Layer",
    "Phishing → Fraudulent Attempt to Steal Information",
  ],
},
{
  title: "Research Ethics Master Sheet",
  items: [
    "Plagiarism → Using Others' Work without Acknowledgment",
    "Self-Plagiarism → Reusing Own Work without Disclosure",
    "Fabrication → Making Up Data",
    "Falsification → Manipulating Data",
    "FFP → Fabrication, Falsification, Plagiarism",
    "Predatory Journal → Charges Fees without Proper Peer Review",
    "Clone Journal → Fake Copy of Genuine Journal",
    "Peer Review → Expert Evaluation before Publication",
    "Retraction → Withdrawal of Published Article",
    "Impact Factor → Citation-Based Journal Metric",
    "Academic Integrity → Honesty and Originality",
    "Publish or Perish → Pressure to Publish",
  ],
},
{
  title: "Reasoning Master Sheet",
  items: [
    "Deductive Reasoning → General to Specific",
    "Inductive Reasoning → Specific to General",
    "Abductive Reasoning → Best Possible Explanation",
    "Syllogism → Conclusion from Premises",
    "Statement and Conclusion → Only follow given information",
    "Statement and Assumption → Hidden belief behind statement",
    "Statement and Argument → Strong vs Weak Argument",
    "Cause and Effect → Identify true causal relationship",
    "Correlation ≠ Causation",
    "Necessary Condition ≠ Sufficient Condition",
    "Contradiction → Opposite truth value",
    "Contrary Propositions → Cannot both be true",
    "Sub-Contrary Propositions → Cannot both be false",
    "Logical Consistency → No contradiction present",
  ],
},
{
  title: "Categorical Proposition Survival Guide",
  items: [
    "A Proposition → All S are P",
    "E Proposition → No S are P",
    "I Proposition → Some S are P",
    "O Proposition → Some S are not P",

    "A → Universal Affirmative",
    "E → Universal Negative",
    "I → Particular Affirmative",
    "O → Particular Negative",

    "A and O → Contradictory",
    "E and I → Contradictory",

    "A and E → Contrary",
    "I and O → Sub-Contrary",

    "A and I → Subalternation",
    "E and O → Subalternation",
  ],
},
{
  title: "Conversion and Contraposition Kill-Shots",
  items: [
    "Conversion → Swap Subject and Predicate",
    "E Proposition converts validly",
    "I Proposition converts validly",
    "A Proposition converts by limitation",
    "O Proposition does NOT convert",

    "Contraposition → Swap and Negate",
    "A Proposition contraposes validly",
    "O Proposition contraposes validly",
    "E Proposition contraposes only by limitation",
    "I Proposition never contraposes validly",

    "Mock Tests repeatedly ask Contraposition",
    "Remember: A and O are Contraposition Friends",
  ],
},
{
  title: "Venn Diagram Survival Guide",
  items: [
    "All A are B → A inside B",
    "No A are B → Separate circles",
    "Some A are B → Overlapping circles",
    "Some A are not B → Part of A outside B",

    "Draw diagram before reading options",
    "Eliminate impossible conclusions first",
    "Do not assume extra information",
    "Only use information provided",
  ],
},
{
  title: "Exam Hall Emergency Rules",
  items: [
    "Read question before options",
    "Eliminate impossible options first",
    "Beware of words: Always, Never, Only, Entirely",
    "Chronology questions require double-checking",
    "Articles are frequent trap areas",
    "Read all statements before selecting answer",
    "In DI, identify Highest, Lowest, Difference, Average first",
    "In English, identify author's argument first",
    "In Fallacies, ask: Is the person attacked or the argument?",
    "Mark doubtful questions and return later",
    "Do not spend more than 90 seconds on one question",
    "Paper 1 marks are your easiest score gain",
  ],
},
{
  title: "PYQ Survival Notes",
  items: [
    "Syllogism: All professors are teachers. All teachers are educated. Therefore, all professors are educated. Shortcut: connect the chain.",
    "Assumption: If government launches a cyber fraud campaign, hidden assumption is that cyber fraud is a serious problem.",
    "Correlation: Ice cream sales and drowning both rise in summer. This does NOT mean ice cream causes drowning. Correlation is not causation.",
    "Reliability vs Validity: A weighing machine gives the same wrong weight daily. It is reliable but not valid.",
    "Sampling: Population divided into male and female groups, then sample taken from each group = Stratified Sampling.",
    "Bloom: If a student designs a new model or framework, it belongs to Create level.",
    "Fallacy: Everyone supports this policy, therefore it is correct = Bandwagon fallacy.",
    "DI: 100 to 300 means increase is 200. Percentage increase = 200/100 × 100 = 200%. Triple value means 200% increase.",
    "Mode: In 10, 20, 20, 30, 40, mode is 20 because it repeats most.",
    "General Will: Rousseau. Trap: not Locke or Hobbes.",
    "Scientific Management: F.W. Taylor. Trap: Fayol is Administrative Management.",
    "Constructivism: 'Anarchy is what states make of it' = Alexander Wendt. Trap: not Waltz.",
  ],
},
{
  title: "PYQ Survival Notes 2",
  items: [
    "Contraposition: All politicians are citizens → All non-citizens are non-politicians. Shortcut: swap and negate.",
    "Conversion Trap: All politicians are citizens does NOT mean all citizens are politicians.",
    "Venn Diagram: All A are B → A circle inside B circle.",
    "Venn Diagram: No A are B → two separate circles.",
    "Venn Diagram: Some A are B → overlapping circles.",
    "NOTA: Introduced after PUCL v. Union of India. Remember: NOTA → PUCL.",
    "CAG: Article 148. Accountable to Parliament.",
    "Finance Commission: Article 280.",
    "Election Commission: Article 324.",
    "SAARC: Mauritius is NOT a member.",
    "Panchamrit: India's climate pledge. Net Zero target = 2070.",
    "NEP 2020: Multidisciplinary education + ABC + multiple entry and exit.",
    "Plagiarism: Using others' work without acknowledgment.",
    "Predatory Journal: Takes publication fee without proper peer review.",
    "DDT: Causes biomagnification in food chain.",
    "Excess Fluoride: Causes fluorosis.",
  ],
},
{
  title: "PYQ Survival Notes 3",
  items: [
    "Hobbes: Sovereign is absolute. No right to rebellion.",
    "Locke: Natural rights + right to rebellion.",
    "Rousseau: General Will.",
    "Bentham: Quantitative Utilitarianism.",
    "J.S. Mill: Qualitative Utilitarianism.",
    "Rawls: Veil of Ignorance.",
    "Nozick: Minimal State.",
    "Lenin: Vanguard Party.",
    "Stalin: Socialism in One Country.",
    "Trotsky: Permanent Revolution.",
    "M.N. Roy: New Humanism.",
    "Lohia: Four-Pillar State.",
    "Tagore: Critique of aggressive nationalism.",
    "Gandhi: Bread Labour.",
    "Ambedkar: Hindu Code Bill controversy.",
    "Weber: Status Groups and Caste Analysis.",
  ],
},
{
  title: "PYQ Survival Notes 4",
  items: [
    "Kesavananda Bharati: Basic Structure Doctrine.",
    "Golaknath: Parliament cannot amend Fundamental Rights.",
    "Minerva Mills: Limited amending power.",
    "Indra Sawhney: Reservation case.",
    "Puttaswamy: Right to Privacy.",
    "Navtej Johar: Section 377 judgment.",
    "42nd Amendment: Mini Constitution.",
    "44th Amendment: Right to Property removed from Fundamental Rights.",
    "52nd Amendment: Anti-Defection Law.",
    "61st Amendment: Voting age reduced to 18.",
    "73rd Amendment: Panchayati Raj.",
    "74th Amendment: Urban Local Bodies.",
    "86th Amendment: Right to Education.",
    "101st Amendment: GST.",
    "103rd Amendment: EWS Reservation.",
  ],
},
{
  title: "30 Second Revision Sheet",
  items: [
    "CAG → 148",
    "Finance Commission → 280",
    "Election Commission → 324",
    "NCSC → 338",
    "NOTA → PUCL",
    "South Sudan → Newest UN Member",
    "Mauritius → NOT SAARC",
    "Manipur → NOT Sixth Schedule",
    "Taylor → Scientific Management",
    "Fayol → Administrative Management",
    "Wendt → Constructivism",
    "Waltz → Neorealism",
    "Morgenthau → Classical Realism",
    "Rawls → Veil of Ignorance",
    "Rousseau → General Will",
    "Lenin → Vanguard Party",
    "Lohia → Four-Pillar State",
    "M.N. Roy → New Humanism",
    "DDT → Biomagnification",
    "Fluorosis → Excess Fluoride",
  ],
},
{
  title: "Paper 1 Most Repeated Patterns",
  items: [
    "Average Question → Given average and number? Multiply them immediately.",
    "Percentage Question → Ask: what fraction is this? 25%=1/4, 50%=1/2, 75%=3/4.",
    "Ratio Question → Add total parts first, then divide total value.",
    "Profit and Loss → CP=100? Then SP directly shows profit/loss percentage.",
    "Probability → Favorable Outcomes ÷ Total Outcomes.",
    "DI Question → Find Highest, Lowest, Difference, Average before reading options.",
    "Reliability vs Validity → Consistent but wrong = Reliable, not Valid.",
    "Sampling Question → Sample taken from EVERY group = Stratified. Only SOME whole groups picked = Cluster.",
    "Bloom Taxonomy → Creating something new = Create level.",
    "Teaching Aptitude → During learning = Formative. End = Summative.",
    "Fallacy Question → Ask: Is argument attacked or person attacked?",
    "English Passage → Find author's main argument before reading options.",
    "Statement & Assumption → Look for hidden belief behind statement.",
    "Statement & Conclusion → Use only given information.",
    "Chronology Question → Eliminate impossible years first.",
  ],
},
{
  title: "DI Emergency Kit",
  items: [
    "Highest Value → Tallest bar.",
    "Lowest Value → Shortest bar.",
    "Difference → Bigger minus smaller.",
    "Average → Add values then divide.",
    "Percentage Increase → (New-Old)/Old × 100.",
    "Double value = 100% increase.",
    "Triple value = 200% increase.",
    "Half value = 50% decrease.",
    "Read all 5 DI questions before calculating.",
    "One calculation often answers multiple questions.",
  ],
},
{
  title: "UGC NET Trap Words",
  items: [
    "Always",
    "Never",
    "Only",
    "Entirely",
    "Completely",
    "All",
    "None",
    "Every",
    "Exclusively",
    "Necessarily",
    "Extreme words are often wrong.",
    "Moderate options are often correct.",
  ],
},
{
  title: "Ghost Exam Hall Strategy",
  items: [
    "Solve English first.",
    "Solve Fallacies second.",
    "Solve DI third.",
    "Solve Teaching Aptitude fourth.",
    "Solve Higher Education fifth.",
    "Mark difficult math and return later.",
    "Do not spend more than 90 seconds on one question.",
    "Chronology questions require double-checking.",
    "Read all statements before selecting answer.",
    "Paper 1 is the easiest place to gain extra marks.",
    "Eliminate wrong options before searching for the correct one.",
    "Trust patterns, not panic.",
  ],
},
{
  title: "PYQ Solved Pattern: Reliability vs Validity",
  items: [
    "Question: A weighing machine gives the same wrong reading every day.",
    "Step 1: Is it consistent? Yes.",
    "Step 2: Is it accurate? No.",
    "Answer: Reliable but not Valid.",
    "Trap: Students think consistency means validity.",
  ],
},
{
  title: "PYQ Solved Pattern: Stratified Sampling",
  items: [
    "Question: Population divided into male and female groups, then sample selected from each.",
    "Step 1: Groups created first.",
    "Step 2: Sample taken from every group.",
    "Answer: Stratified Sampling.",
    "Trap: Often confused with Cluster Sampling.",
  ],
},
{
  title: "PYQ Solved Pattern: Correlation",
  items: [
    "Question: Ice cream sales and drowning deaths increase together.",
    "Step 1: Relationship exists.",
    "Step 2: Does one cause the other? No.",
    "Answer: Correlation does not imply causation.",
    "Trap: NTA loves this concept.",
  ],
},
{
  title: "PYQ Solved Pattern: Bloom Taxonomy",
  items: [
    "Question: Student develops a new policy framework.",
    "Step 1: Is something new being produced? Yes.",
    "Answer: Create.",
    "Remember: Create is highest level.",
    "Trap: Students choose Evaluate.",
  ],
},
{
  title: "PYQ Solved Pattern: Formative vs Summative",
  items: [
    "Question: Teacher evaluates students continuously during course.",
    "Step 1: During learning?",
    "Answer: Formative Evaluation.",
    "End of course?",
    "Answer: Summative Evaluation.",
    "Trap: During = Formative, End = Summative.",
  ],
},
{
  title: "PYQ Solved Pattern: Contraposition",
  items: [
    "Question: All politicians are citizens.",
    "Step 1: Identify A proposition.",
    "Step 2: Swap subject and predicate.",
    "Step 3: Negate both.",
    "Answer: All non-citizens are non-politicians.",
    "Trap: Students write 'All citizens are politicians' (conversion).",
  ],
},
{
  title: "PYQ Solved Pattern: Ad Hominem",
  items: [
    "Question: Do not listen to his argument on taxation. He failed economics.",
    "Step 1: Is the argument attacked?",
    "No.",
    "Step 2: Is the person attacked?",
    "Yes.",
    "Answer: Ad Hominem.",
    "Trap: Ignore the topic. Focus on attack pattern.",
  ],
},
{
  title: "PYQ Solved Pattern: General Will",
  items: [
    "Question: Who proposed General Will?",
    "Keyword: General Will.",
    "Answer: Rousseau.",
    "Trap: Locke = Natural Rights, Hobbes = Sovereign.",
  ],
},
{
  title: "Most Repeated NET Confusions",
  items: [
    "Reliability = Consistency | Validity = Accuracy",
    "Stratified Sampling = Sample from every group | Cluster Sampling = Pick some whole groups",
    "Taylor = Scientific Management | Fayol = Administrative Management",
    "Rawls = Welfare Justice | Nozick = Minimal State",
    "Morgenthau = Classical Realism | Waltz = Neorealism",
    "Locke = Limited Government | Hobbes = Absolute Sovereign",
    "Formative = During Learning | Summative = End of Learning",
    "Correlation = Relationship | Causation = Cause-Effect",
    "Mean = Average | Median = Middle | Mode = Most Repeated",
    "Plagiarism = Others' Work | Self-Plagiarism = Own Work Reused",
    "Constructivism = Wendt | Neoliberalism = Keohane",
    "General Will = Rousseau | Natural Rights = Locke",
    "Behavioralism = Scientific Study | Post-Behavioralism = Relevance",
    "Positive Liberty = Freedom To | Negative Liberty = Freedom From",
    "Panchayati Raj = 73rd Amendment | Municipalities = 74th Amendment",
  ],
},
{
  title: "One Question One Trigger",
  items: [
    "General Will → Rousseau",
    "Veil of Ignorance → Rawls",
    "Minimal State → Nozick",
    "New Humanism → M.N. Roy",
    "Four-Pillar State → Lohia",
    "Bread Labour → Gandhi",
    "Vanguard Party → Lenin",
    "Permanent Revolution → Trotsky",
    "Socialism in One Country → Stalin",
    "Cultural Hegemony → Gramsci",
    "Political Animal → Aristotle",
    "Philosopher King → Plato",
    "Anarchy is what states make of it → Wendt",
    "Soft Power → Joseph Nye",
    "Clash of Civilizations → Huntington",
    "End of History → Fukuyama",
    "Civic Culture → Almond and Verba",
    "Iron Law of Oligarchy → Michels",
    "Circulation of Elites → Pareto",
    "Power Elite → C. Wright Mills",
  ],
},
{
  title: "Last 15 Minutes Before Exam",
  items: [
    "CAG → 148",
    "Finance Commission → 280",
    "Election Commission → 324",
    "NCSC → 338",
    "NOTA → PUCL",
    "South Sudan → Newest UN Member",
    "Mauritius → NOT SAARC",
    "Manipur → NOT Sixth Schedule",
    "Taylor → Scientific Management",
    "Fayol → Administrative Management",
    "Rousseau → General Will",
    "Rawls → Veil of Ignorance",
    "Nozick → Minimal State",
    "Lenin → Vanguard Party",
    "M.N. Roy → New Humanism",
    "Lohia → Four-Pillar State",
    "DDT → Biomagnification",
    "Fluorosis → Excess Fluoride",
    "NEP 2020 → ABC + Multiple Entry Exit",
    "Wendt → Constructivism",
  ],
},
{
  title: "Reading Comprehension Survival Guide",
  items: [
    "Main Idea Question → Ask: What is the whole passage mainly about?",
    "Inference Question → Answer is not directly stated but supported by passage.",
    "Tone Question → Usually Neutral, Critical, Analytical, or Concerned.",
    "Author's Argument → Find repeated idea in first and last paragraph.",
    "Assumption Question → Hidden belief behind the argument.",
    "Fallacy Question → Identify the weakness in reasoning.",
    "Vocabulary Question → Use context, not dictionary meaning.",
    "Extreme Options → Always, Never, Only, Completely are usually traps.",
    "Best Answer → Choose option most directly supported by passage.",
    "Do not bring outside knowledge into comprehension.",
    "Read questions first if passage is too long.",
    "For research passages, look for problem, cause, effect, solution.",
  ],
},
{
  title: "English Passage Trap Notes",
  items: [
    "If option is too emotional, usually wrong.",
    "If option is too extreme, usually wrong.",
    "If option adds outside knowledge, usually wrong.",
    "If option repeats passage idea in simpler words, often correct.",
    "Author's tone is rarely angry; usually critical or analytical.",
    "Inference must be supported, not imagined.",
    "Main idea is broader than one paragraph.",
    "Title question → choose the option covering the whole passage.",
    "Conclusion question → choose what naturally follows from passage.",
    "Assumption question → ask what must be true for argument to stand.",
  ],
},
{
  title: "50-50 Trap Questions",
  items: [
    "Reliability but not Validity → Possible",
    "Validity without Reliability → Generally impossible",
    "Correlation does not imply Causation",
    "Association does not imply Cause",
    "Necessary condition is not always Sufficient",
    "Sufficient condition is not always Necessary",
    "All A are B does NOT mean all B are A",
    "Some A are B does NOT mean all A are B",
    "Popularity does not prove Truth",
    "Expert opinion is not proof",
    "Chronology questions often contain one wrong year",
    "Extreme statements are usually incorrect",
    "UGC loves one-word traps",
  ],
},
{
  title: "Indian Government and Politics Kill-Shots",
  items: [
    "Article 356 → President's Rule",
    "Article 352 → National Emergency",
    "Article 360 → Financial Emergency",
    "Money Bill → Article 110",
    "Constitution Amendment → Article 368",
    "Attorney General → Article 76",
    "Advocate General → Article 165",
    "Governor → Article 153",
    "Inter-State Council → Article 263",
    "Finance Commission → Article 280",
    "Election Commission → Article 324",
    "CAG → Article 148",
  ],
},
{
  title: "Governance War Room",
  items: [
    "Good Governance → Accountability, Transparency, Participation",
    "E-Governance → Use of ICT in government",
    "SMART Governance → Simple, Moral, Accountable, Responsive, Transparent",
    "Citizen Charter → Public service commitment",
    "Social Audit → Public review of government programs",
    "RTI Act → 2005",
    "Lokpal Act → 2013",
    "Digital Governance → Technology in administration",
    "Public Accountability → Responsibility to citizens",
    "Participatory Governance → Citizen involvement in decision-making",
  ],
},
{
  title: "Higher Education Super Traps",
  items: [
    "UGC established → 1953",
    "UGC Act → 1956",
    "NAAC → Bengaluru",
    "NAAC established → 1994",
    "NIRF launched → 2015",
    "ABC → Academic Bank of Credits",
    "HECI → Higher Education Commission of India",
    "GER Target → 50% by 2035",
    "NEP School Structure → 5+3+3+4",
    "1-Year Exit → Certificate",
    "2-Year Exit → Diploma",
    "3-Year Exit → Degree",
    "4-Year Exit → Honours Degree (or Honours with Research)",
    "IKS → Indian Knowledge Systems",
    "SWAYAM → MOOCs Platform",
    "MOOC → Massive Open Online Course",
  ],
},
{
  title: "Ancient Universities War Room",
  items: [
    "Nalanda → Bihar",
    "Takshashila → Present-day Pakistan",
    "Vikramashila → Bihar",
    "Vallabhi → Gujarat",
    "Odantapuri → Bihar",
    "Pushpagiri → Odisha",
    "Mithila → Bihar",
    "Nalanda founded by → Kumaragupta I",
    "Xuanzang studied at → Nalanda",
    "Takshashila is older than Nalanda",
    "Ancient Indian education → Oral tradition",
    "Shravana → Hearing",
    "Manana → Reflection",
    "Nididhyasana → Realization",
    "Goal of Ancient Education → Moksha",
    "Maktab → Primary Islamic education",
    "Madrasa → Higher Islamic education",
    "Bismillah Rasam → Admission ceremony",
    "Age for Bismillah Rasam → 4 years, 4 months, 4 days",
  ],
},
{
  title: "Feminism War Room",
  items: [
    "Mary Wollstonecraft → Liberal Feminism",
    "Simone de Beauvoir → The Second Sex",
    "Betty Friedan → The Feminine Mystique",
    "Kate Millett → Sexual Politics",
    "Liberal Feminism → Equal rights",
    "Radical Feminism → Patriarchy as oppression",
    "Socialist Feminism → Gender and class oppression",
    "Ecofeminism → Women and environment",
    "Intersectionality → Kimberlé Crenshaw",
    "Fourth Wave Feminism → Digital activism",
  ],
},
{
  title: "Marxism War Room",
  items: [
    "Base → Economic structure",
    "Superstructure → Political and legal institutions",
    "Alienation → Separation from labour",
    "Surplus Value → Profit from labour exploitation",
    "Class Struggle → Motor of history",
    "Historical Materialism → Material conditions drive change",
    "Dialectical Materialism → Contradiction creates change",
    "Bourgeoisie → Owners",
    "Proletariat → Workers",
    "Communism → Classless society",
  ],
},
{
  title: "Political Economy War Room",
  items: [
    "Adam Smith → Invisible Hand",
    "David Ricardo → Comparative Advantage",
    "Karl Marx → Historical Materialism",
    "Keynes → State Intervention",
    "Hayek → Free Market",
    "Amartya Sen → Capability Approach",
    "Dependency Theory → Andre Gunder Frank",
    "World Systems Theory → Immanuel Wallerstein",
    "Neo-Liberalism → Market-led development",
    "Political Economy → Relationship between politics and economics",
  ],
},

];
 return (
    <main className="min-h-screen bg-slate-950 text-white p-6">
      <h1 className="text-3xl font-bold text-purple-300">
        UGC NET Paper 2
      </h1>

      <p className="mt-4 text-slate-300">
        Political Science bypass notes for fast revision before exam.
      </p>

      <div className="mt-8 space-y-6">
        {trapSections.map((section) => (
          <section
            key={section.title}
            className="rounded-2xl border border-slate-700 bg-slate-900 p-5"
          >
            <h2 className="text-xl font-bold text-yellow-300 mb-4">
              {section.title}
            </h2>

            <div className="space-y-2">
              {section.items.map((item) => (
                <div
                  key={item}
                  className="rounded-lg bg-slate-800 px-4 py-3 text-slate-200"
                >
                  {item}
                </div>
              ))}
            </div>
          </section>
        ))}
      </div>
    </main>
  );
}