import type { MCQ, Source } from "./questions";

type Unit2 =
  | "Political Theory"
  | "Western Thought"
  | "Indian Thought"
  | "Comparative Politics"
  | "International Relations"
  | "India's Foreign Policy"
  | "Political Institutions"
  | "Political Processes"
  | "Public Administration"
  | "Governance & Policy";

function q(
  id: string,
  paper: 1 | 2,
  unit: string,
  format: MCQ["format"],
  question: string,
  options: [string, string, string, string],
  answer: 0 | 1 | 2 | 3,
  explain: string,
  source?: Source,
): MCQ {
  return { id, paper, unit, format, question, options, answer, explain, source };
}

const p2 = (
  id: string,
  unit: Unit2,
  format: MCQ["format"],
  question: string,
  options: [string, string, string, string],
  answer: 0 | 1 | 2 | 3,
  explain: string,
  source?: Source,
) => q(id, 2, unit, format, question, options, answer, explain, source);

const TB = "https://testbook.com/question-answer/";

export const morePaper2: MCQ[] = [
  // ---------- Past-paper confirmed (second search round) ----------
  p2("s1", "Indian Thought", "Direct",
    "Pandita Ramabai was associated with which mission?",
    ["Ramakrishna Mission", "Mukti Mission", "Servants of India Society", "Satyashodhak Samaj"], 1,
    "Mukti Mission at Kedgaon (late 1890s), for widows and destitute women. Her earlier Sharada Sadan dates from 1889.",
    { kind: "pyq", label: "PYQ (PW Unit 3 PYQs)", url: "https://www.pw.live/ugc-net/exams/ugc-net-political-science-unit-3-pyqs" }),
  p2("s2", "Political Processes", "Direct",
    "Which of the following is NOT a feature of Yogendra Yadav's 'Third Electoral System' (1989–99)?",
    ["Democratic upsurge of lower castes", "Political fragmentation", "Post-Congress polity", "Strengthening of elite control"], 3,
    "The third electoral system weakened elite control through a 'second democratic upsurge'.",
    { kind: "pyq", label: "PYQ (Testbook): Third Electoral System", url: TB + "yogendra-yadav-introduced-a-concept-of-third-elect--68acf99d47e12868b2205ce6" }),
  p2("s3", "Western Thought", "Statements",
    "Which two are correct? (a) Plato laid more emphasis on duties than rights. (b) His ideal state was merely an idea, not reality. (c) Plato favoured private property for guardians. (d) Plato's ideal state rested on the rule of written law.",
    ["(a) and (b)", "(b) and (c)", "(a) and (d)", "(c) and (d)"], 0,
    "Guardians live under communism of property and family. Rule of law is the 'second-best' state of The Laws.",
    { kind: "pyq", label: "PYQ Dec 2019 (Testbook)", url: TB + "which-of-the-following-two-are-correcta-plato--6347d39625f323f9dc22c742" }),
  p2("s4", "Western Thought", "Direct",
    "In which book of 'Politics' does Aristotle justify slavery?",
    ["Book I", "Book III", "Book V", "Book VII"], 0,
    "Book I argues some people are 'slaves by nature'. Book III covers citizenship and constitutions, and Book V revolutions.",
    { kind: "pyq", label: "PYQ Oct 2022 (Testbook)", url: TB + "in-which-of-the-following-books-of-politics--63c17e9646fa2aa58fbd8970" }),
  p2("s5", "Western Thought", "Direct",
    "Karl Popper attacked the historicism of:",
    ["Plato and Hegel", "Locke and Hume", "Kant and Rousseau", "Aristotle and Aquinas"], 0,
    "The Open Society and Its Enemies (1945): Plato in Vol. I, Hegel and Marx in Vol. II.",
    { kind: "pyq", label: "PYQ Nov 2021 (Testbook)", url: TB + "karl-popper-attacked-the-historicism-of--6285fac4e4d278df79f021aa" }),
  p2("s6", "Western Thought", "Direct",
    "Who is credited with first using the term 'State' (lo stato) in its modern sense?",
    ["Bodin", "Machiavelli", "Hobbes", "Aristotle"], 1,
    "Machiavelli, especially in The Prince. Bodin gave the modern theory of sovereignty.",
    { kind: "topic", label: "PYQ topic (Testbook)", url: TB + "who-had-given-the-term-state--5ecf57cbf60d5d5714fedbb7" }),
  p2("s7", "Political Institutions", "Statements",
    "Which have been read into Article 21 by the courts? A. Right to livelihood  B. Right to reputation  C. Sustainable development / clean environment  D. Free education up to 16 years  E. Right to privacy",
    ["A, B, C and E only", "A, B, D and E only", "B, C and D only", "A, B, C, D and E"], 0,
    "D is wrong: Article 21A guarantees free education for ages 6–14, not 16.",
    { kind: "pyq", label: "PYQ June 2023 (Testbook)", url: TB + "which-of-the-following-rights-are-declared-as-fund--64abc9d9a36c25f49f8b89bf" }),
  p2("s8", "Governance & Policy", "Direct",
    "Which body first recommended the setting up of Lokpal and Lokayukta to redress citizens' grievances?",
    ["Santhanam Committee", "First Administrative Reforms Commission", "Second Administrative Reforms Commission", "Sarkaria Commission"], 1,
    "The 1st ARC's interim report (1966). Santhanam (1962–64) led to the CVC.",
    { kind: "topic", label: "PYQ topic, June 2023 (Testbook)", url: TB + "who-recommended-the-setting-up-of-two-special-auth--6953be2b6c223f42105e60b3" }),
  p2("s9", "Governance & Policy", "Direct",
    "The Right to Information Act came fully into force on:",
    ["15 June 2005", "12 October 2005", "26 January 2006", "2 October 2005"], 1,
    "Passed 15 June 2005; fully in force 12 October 2005.",
    { kind: "topic", label: "PYQ topic (Testbook RTI set)", url: "https://testbook.com/ugc-net-political-science/rti-act-2005-and-amendment" }),
  p2("s10", "Indian Thought", "Direct",
    "Which thinker was a trenchant critic of Aryanism, Brahmanism and Hinduism and launched the Self-Respect Movement?",
    ["Narayana Guru", "E.V. Ramasamy 'Periyar'", "Ayyankali", "C.N. Annadurai"], 1,
    "Periyar (1925). Annadurai was his follower who founded the DMK in 1949.",
    { kind: "topic", label: "PYQ topic (PW Unit 3 PYQs)", url: "https://www.pw.live/ugc-net/exams/ugc-net-political-science-unit-3-pyqs" }),

  // ---------- Political Theory ----------
  p2("x1", "Political Theory", "Direct", "'A Grammar of Politics' (1925) was written by:",
    ["Harold Laski", "Ernest Barker", "R.M. MacIver", "G.D.H. Cole"], 0, "Laski, a pluralist who later moved towards Marxism."),
  p2("x2", "Political Theory", "Direct", "Which of the following is NOT a pluralist thinker on sovereignty?",
    ["Harold Laski", "F.W. Maitland", "J.N. Figgis", "John Austin"], 3, "Austin's theory is the classic monistic one, which the pluralists attacked."),
  p2("x3", "Political Theory", "Direct", "Sovereignty as the 'command of a determinate human superior' is the theory of:",
    ["Jean Bodin", "John Austin", "Thomas Hobbes", "Hugo Krabbe"], 1, "Austin, The Province of Jurisprudence Determined (1832)."),
  p2("x4", "Political Theory", "Direct", "'Equality' (1931), a classic defence of socialist equality, was written by:",
    ["R.H. Tawney", "Harold Laski", "Bernard Crick", "T.H. Marshall"], 0, "Tawney. T.H. Marshall wrote Citizenship and Social Class (1950)."),
  p2("x5", "Political Theory", "Direct", "'Justice is the interest of the stronger' is argued in the Republic by:",
    ["Glaucon", "Cephalus", "Thrasymachus", "Polemarchus"], 2, "Thrasymachus in Book I. Cephalus: telling the truth and paying debts. Polemarchus: help friends, harm enemies."),
  p2("x6", "Political Theory", "Direct", "Which of the following is NOT a communitarian critic of Rawls?",
    ["Michael Sandel", "Alasdair MacIntyre", "Charles Taylor", "Robert Nozick"], 3, "Nozick criticised Rawls from the libertarian side."),
  p2("x7", "Political Theory", "Direct", "'Polyarchy' (1971) as a name for real-world democracies was coined by:",
    ["Robert Dahl", "Joseph Schumpeter", "Giovanni Sartori", "Seymour Lipset"], 0, "Dahl: contestation plus participation."),
  p2("x8", "Political Theory", "Direct", "Democracy as a 'competitive struggle for the people's vote' among elites is the view of:",
    ["Robert Dahl", "Joseph Schumpeter", "C.B. Macpherson", "Carole Pateman"], 1, "Schumpeter, Capitalism, Socialism and Democracy (1942)."),
  p2("x9", "Political Theory", "Direct", "'The End of Ideology' (1960) was written by:",
    ["Francis Fukuyama", "Daniel Bell", "Edward Shils", "S.M. Lipset"], 1, "Bell. Fukuyama's 'End of History' is 1989/1992, a classic confusion pair."),
  p2("x10", "Political Theory", "Direct", "'The Politics of Recognition' (1992) is an essay by:",
    ["Axel Honneth", "Charles Taylor", "Nancy Fraser", "Will Kymlicka"], 1, "Taylor. Honneth wrote The Struggle for Recognition, which is the trap."),
  p2("x11", "Political Theory", "Direct", "'Rethinking Multiculturalism' (2000) was written by:",
    ["Bhikhu Parekh", "Will Kymlicka", "Rajeev Bhargava", "Amartya Sen"], 0, "Parekh. Kymlicka wrote Multicultural Citizenship (1995)."),
  p2("x12", "Political Theory", "Direct", "'Rights as trumps' is a formulation of:",
    ["H.L.A. Hart", "Ronald Dworkin", "Joseph Raz", "John Finnis"], 1, "Dworkin, Taking Rights Seriously (1977)."),
  p2("x13", "Political Theory", "Direct", "The 'three-dimensional view' of power was given by:",
    ["Robert Dahl", "Bachrach and Baratz", "Steven Lukes", "Michel Foucault"], 2, "Lukes, Power: A Radical View (1974). Dahl is the 1st dimension and Bachrach & Baratz the 2nd ('two faces')."),
  p2("x14", "Political Theory", "Direct", "'Deep ecology' was coined by:",
    ["Arne Naess", "Murray Bookchin", "Rachel Carson", "Aldo Leopold"], 0, "Naess (1973). Bookchin: social ecology. Carson: Silent Spring (1962)."),
  p2("x15", "Political Theory", "Direct", "The 'capability approach' to justice and development is associated with:",
    ["Rawls and Nozick", "Sen and Nussbaum", "Walzer and Sandel", "Dworkin and Raz"], 1, "Sen (from 1979) and Martha Nussbaum's list of central capabilities."),
  p2("x16", "Political Theory", "Chronology", "Arrange: A. A Theory of Justice  B. On Liberty  C. Anarchy, State and Utopia  D. The Subjection of Women",
    ["B, D, A, C", "D, B, A, C", "B, D, C, A", "B, A, D, C"], 0, "1859 → 1869 → 1971 → 1974."),
  p2("x17", "Political Theory", "Assertion-Reason",
    "A: T.H. Green justified state action to remove hindrances to the good life. R: Green understood freedom as a positive power of doing something worth doing.",
    ["Both true, R explains A", "Both true, R does not explain A", "A true, R false", "A false, R true"], 0,
    "His positive idea of freedom is exactly why the state should 'hinder hindrances'."),
  p2("x18", "Political Theory", "Direct", "'The Ruling Class' (Elementi di scienza politica) was written by:",
    ["Vilfredo Pareto", "Gaetano Mosca", "Robert Michels", "James Burnham"], 1, "Mosca. Pareto: circulation of elites. Michels: iron law of oligarchy."),
  p2("x19", "Political Theory", "Direct", "Deliberative democracy grounded in 'communicative action' is most associated with:",
    ["Jürgen Habermas", "Niklas Luhmann", "Anthony Giddens", "Ulrich Beck"], 0, "Habermas, Theory of Communicative Action (1981)."),
  p2("x20", "Political Theory", "Direct", "'The Second Sex' (1949) was written by:",
    ["Betty Friedan", "Simone de Beauvoir", "Kate Millett", "Shulamith Firestone"], 1, "'One is not born, but rather becomes, a woman.'"),

  // ---------- Western Thought ----------
  p2("x21", "Western Thought", "Direct", "'Man is by nature a political animal' is from:",
    ["Plato's Republic", "Aristotle's Politics", "Cicero's De Re Publica", "Aquinas's Summa"], 1, "Aristotle, Politics Book I."),
  p2("x22", "Western Thought", "Direct", "Which is NOT one of Aquinas's four kinds of law?",
    ["Eternal law", "Natural law", "Divine law", "Customary law"], 3, "Eternal, natural, divine and human law."),
  p2("x23", "Western Thought", "Direct", "'Six Books of the Commonwealth' (1576), with its theory of sovereignty, was written by:",
    ["Jean Bodin", "Hugo Grotius", "Thomas Hobbes", "Johannes Althusius"], 0, "Bodin defined sovereignty as absolute and perpetual power."),
  p2("x24", "Western Thought", "Direct", "The separation of powers was systematically argued in 'The Spirit of the Laws' (1748) by:",
    ["Locke", "Montesquieu", "Rousseau", "Madison"], 1, "Montesquieu, drawing on his reading of the English constitution."),
  p2("x25", "Western Thought", "Direct", "'Reflections on the Revolution in France' (1790) was written by:",
    ["Thomas Paine", "Edmund Burke", "Joseph de Maistre", "Alexis de Tocqueville"], 1, "Burke. Paine replied with Rights of Man (1791)."),
  p2("x26", "Western Thought", "Direct", "Plural voting for the educated was proposed in 'Considerations on Representative Government' by:",
    ["Jeremy Bentham", "J.S. Mill", "James Mill", "Walter Bagehot"], 1, "J.S. Mill (1861), who also supported Hare's proportional representation."),
  p2("x27", "Western Thought", "Direct", "Life in the state of nature as 'solitary, poor, nasty, brutish, and short' is from:",
    ["Locke", "Hobbes", "Rousseau", "Spinoza"], 1, "Hobbes, Leviathan, Chapter 13."),
  p2("x28", "Western Thought", "Direct", "The idea of 'tacit consent' to government is associated with:",
    ["Hobbes", "Locke", "Rousseau", "Hume"], 1, "Locke, Second Treatise. Hume later criticised consent theory."),
  p2("x29", "Western Thought", "Chronology", "Arrange: A. Spirit of the Laws  B. Six Books of the Commonwealth  C. Reflections on the Revolution in France  D. Leviathan",
    ["B, D, A, C", "D, B, A, C", "B, A, D, C", "B, D, C, A"], 0, "1576 → 1651 → 1748 → 1790."),
  p2("x30", "Western Thought", "Direct", "'Imperialism, the Highest Stage of Capitalism' was written by:",
    ["Rosa Luxemburg", "Lenin", "Hobson", "Bukharin"], 1, "Lenin (1916, published 1917). Hobson's Imperialism (1902) influenced it."),
  p2("x31", "Western Thought", "Direct", "'Ideological State Apparatuses' is a concept of:",
    ["Gramsci", "Louis Althusser", "Nicos Poulantzas", "Ralph Miliband"], 1, "Althusser (1970): school, church, family and media, as opposed to repressive apparatuses."),
  p2("x32", "Western Thought", "Direct", "'One-Dimensional Man' (1964) was written by:",
    ["Herbert Marcuse", "Theodor Adorno", "Max Horkheimer", "Erich Fromm"], 0, "Marcuse, of the Frankfurt School."),
  p2("x33", "Western Thought", "Direct", "The 'Communist Manifesto' was published in:",
    ["1844", "1848", "1859", "1867"], 1, "1848. 1859 is A Contribution to the Critique of Political Economy and 1867 is Capital Vol. I."),
  p2("x34", "Western Thought", "Direct", "'Discourse on the Origin of Inequality' (1755) was written by:",
    ["Voltaire", "Rousseau", "Diderot", "Montesquieu"], 1, "Rousseau: private property as the source of inequality."),
  p2("x35", "Western Thought", "Direct", "'The City of God' was written by:",
    ["St. Augustine", "St. Thomas Aquinas", "Marsilius of Padua", "Dante"], 0, "Augustine (early 5th century). Marsilius wrote Defensor Pacis."),
  p2("x36", "Western Thought", "Match", "Match: A. Bentham  B. Hegel  C. Burke  D. Bodin — I. Sovereignty  II. Prescription and tradition  III. Panopticon  IV. Philosophy of Right",
    ["A-III, B-IV, C-II, D-I", "A-IV, B-III, C-II, D-I", "A-III, B-II, C-IV, D-I", "A-III, B-IV, C-I, D-II"], 0, "Bentham and Hegel alone lock it."),

  // ---------- Indian Thought ----------
  p2("x37", "Indian Thought", "Chronology", "Arrange by founding: A. Arya Samaj  B. Brahmo Samaj  C. Servants of India Society  D. Ramakrishna Mission",
    ["B, A, D, C", "A, B, D, C", "B, D, A, C", "B, A, C, D"], 0, "1828 → 1875 → 1897 → 1905."),
  p2("x38", "Indian Thought", "Direct", "'Satyarth Prakash' (1875) was written by:",
    ["Swami Vivekananda", "Dayanand Saraswati", "Raja Ram Mohan Roy", "Keshab Chandra Sen"], 1, "Dayanand, founder of the Arya Samaj."),
  p2("x39", "Indian Thought", "Direct", "'Gita Rahasya' was written by Tilak while imprisoned at:",
    ["Andaman", "Mandalay", "Yerwada", "Ahmednagar Fort"], 1, "Mandalay (1908–14). Nehru wrote Discovery of India in Ahmednagar Fort."),
  p2("x40", "Indian Thought", "Direct", "The Servants of India Society (1905) was founded by:",
    ["Tilak", "G.K. Gokhale", "Ranade", "Pherozeshah Mehta"], 1, "Gokhale, whom Gandhi called his political guru."),
  p2("x41", "Indian Thought", "Direct", "'The Doctrine of Passive Resistance' (1907) was written by:",
    ["Gandhi", "Aurobindo Ghosh", "Bipin Chandra Pal", "Lala Lajpat Rai"], 1, "Aurobindo, in Bande Mataram, before his turn to spirituality."),
  p2("x42", "Indian Thought", "Direct", "The Satyashodhak Samaj was founded in 1873 by:",
    ["Jyotiba Phule", "B.R. Ambedkar", "Shahu Maharaj", "Narayana Guru"], 0, "Phule, the same year as Gulamgiri."),
  p2("x43", "Indian Thought", "Direct", "The Mahad Satyagraha (1927) led by Ambedkar concerned:",
    ["Temple entry", "Access to public water (Chavdar tank)", "Separate electorates", "Land rights"], 1, "Chavdar tank, Mahad. Kalaram temple entry was in 1930, at Nashik."),
  p2("x44", "Indian Thought", "Direct", "'Sarvodaya' was Gandhi's rendering of the ideas in:",
    ["Tolstoy's The Kingdom of God Is Within You", "Ruskin's Unto This Last", "Thoreau's Civil Disobedience", "Carpenter's Civilisation"], 1, "Gandhi translated Ruskin's book as 'Sarvodaya' in 1908."),
  p2("x45", "Indian Thought", "Direct", "The Bhoodan movement began in 1951 at Pochampalli under:",
    ["J.P. Narayan", "Vinoba Bhave", "Ram Manohar Lohia", "Acharya Kripalani"], 1, "Vinoba Bhave, in Telangana."),
  p2("x46", "Indian Thought", "Direct", "'Saptakranti' (seven revolutions) is associated with:",
    ["J.P. Narayan", "Ram Manohar Lohia", "M.N. Roy", "Narendra Deva"], 1, "Lohia. JP is 'Total Revolution', which is the trap."),
  p2("x47", "Indian Thought", "Direct", "Which is NOT part of Kautilya's six-fold foreign policy (Shadgunya)?",
    ["Sandhi", "Vigraha", "Asana", "Danda"], 3, "Sandhi, Vigraha, Asana, Yana, Samshraya and Dvaidhibhava. Danda is a Saptanga element and one of the four upayas."),
  p2("x48", "Indian Thought", "Direct", "'The Discovery of India' was written by Nehru in:",
    ["Naini jail", "Ahmednagar Fort", "Dehradun jail", "Almora jail"], 1, "Ahmednagar Fort (1942–46)."),
  p2("x49", "Indian Thought", "Match", "Match: A. Dayanand  B. Phule  C. Periyar  D. Narayana Guru — I. Self-Respect Movement  II. Arya Samaj  III. SNDP Yogam  IV. Satyashodhak Samaj",
    ["A-II, B-IV, C-I, D-III", "A-IV, B-II, C-I, D-III", "A-II, B-I, C-IV, D-III", "A-II, B-IV, C-III, D-I"], 0, "SNDP (1903) is Narayana Guru's movement in Kerala."),
  p2("x50", "Indian Thought", "Direct", "Iqbal's 1930 presidential address proposing a consolidated north-west Muslim state was at:",
    ["Lahore", "Allahabad", "Karachi", "Aligarh"], 1, "Allahabad, Muslim League session, 1930. The Lahore Resolution was 1940."),
  p2("x51", "Indian Thought", "Direct", "Gandhi's idea that the rich should hold wealth for the welfare of society is:",
    ["Swadeshi", "Trusteeship", "Bread labour", "Aparigraha"], 1, "Trusteeship. Aparigraha (non-possession) is the personal vow behind it."),

  // ---------- Comparative Politics ----------
  p2("x52", "Comparative Politics", "Direct", "'Political Order in Changing Societies' (1968) was written by:",
    ["Lucian Pye", "Samuel Huntington", "Gabriel Almond", "David Apter"], 1, "Huntington: institutionalisation must keep pace with participation, or there is decay."),
  p2("x53", "Comparative Politics", "Direct", "'Social Origins of Dictatorship and Democracy' (1966) was written by:",
    ["Barrington Moore Jr.", "Theda Skocpol", "Charles Tilly", "Perry Anderson"], 0, "Moore: 'No bourgeoisie, no democracy'."),
  p2("x54", "Comparative Politics", "Direct", "Theda Skocpol's 'States and Social Revolutions' (1979) compares revolutions in:",
    ["France, Russia, China", "England, France, USA", "Russia, Cuba, Iran", "Mexico, China, Vietnam"], 0, "A state-centred, structural account."),
  p2("x55", "Comparative Politics", "Direct", "'Bureaucratic authoritarianism' was theorised by:",
    ["Juan Linz", "Guillermo O'Donnell", "Alfred Stepan", "Philippe Schmitter"], 1, "O'Donnell (1973), on Argentina and Brazil."),
  p2("x56", "Comparative Politics", "Direct", "'Making Democracy Work' (1993), on social capital in Italy, was written by:",
    ["Robert Putnam", "Sidney Verba", "Francis Fukuyama", "James Coleman"], 0, "Putnam, who also wrote Bowling Alone (2000)."),
  p2("x57", "Comparative Politics", "Direct", "In Almond's scheme, which is an OUTPUT function?",
    ["Interest articulation", "Political socialisation", "Rule adjudication", "Interest aggregation"], 2, "Outputs are rule-making, rule-application and rule-adjudication. The rest are inputs."),
  p2("x58", "Comparative Politics", "Direct", "In Easton's systems model, the inputs are:",
    ["Demands and supports", "Decisions and actions", "Feedback and outputs", "Rules and sanctions"], 0, "Inputs are demands and supports. Outputs are decisions and actions."),
  p2("x59", "Comparative Politics", "Direct", "Societal corporatism ('Still the Century of Corporatism?', 1974) is associated with:",
    ["Philippe Schmitter", "Gerhard Lehmbruch", "Robert Dahl", "Theodore Lowi"], 0, "Schmitter."),
  p2("x60", "Comparative Politics", "Direct", "Switzerland's federal executive, a 7-member Federal Council, is an example of:",
    ["Presidential executive", "Parliamentary executive", "Collegial (directorial) executive", "Semi-presidential executive"], 2, "A collegial or directorial executive."),
  p2("x61", "Comparative Politics", "Direct", "Mixed-member proportional representation is classically associated with:",
    ["UK", "Germany", "USA", "France"], 1, "Germany. France uses a two-round system and the UK first-past-the-post."),
  p2("x62", "Comparative Politics", "Direct", "'Political Man' (1960), linking economic development and democracy, was written by:",
    ["S.M. Lipset", "Robert Dahl", "Daniel Lerner", "W.W. Rostow"], 0, "Lipset's modernisation thesis."),
  p2("x63", "Comparative Politics", "Direct", "'Patterns of Democracy' (1999) contrasted majoritarian and consensus models using 36 democracies. Its author is:",
    ["Arend Lijphart", "G. Bingham Powell", "Juan Linz", "Larry Diamond"], 0, "Lijphart."),
  p2("x64", "Comparative Politics", "Direct", "The original US Constitution contains how many Articles?",
    ["5", "7", "10", "27"], 1, "7 Articles. 27 is the number of amendments, and 10 the Bill of Rights."),
  p2("x65", "Comparative Politics", "Direct", "'The Stages of Economic Growth: A Non-Communist Manifesto' (1960) was written by:",
    ["W.W. Rostow", "A.G. Frank", "Daniel Lerner", "Raúl Prebisch"], 0, "Rostow, a classic modernisation theorist."),

  // ---------- International Relations ----------
  p2("x66", "International Relations", "Direct", "'The Twenty Years' Crisis, 1919–1939' was written by:",
    ["Hans Morgenthau", "E.H. Carr", "Reinhold Niebuhr", "Martin Wight"], 1, "Carr's realist critique of 'utopian' liberalism."),
  p2("x67", "International Relations", "Direct", "Functionalism in international integration ('A Working Peace System') is associated with:",
    ["David Mitrany", "Ernst Haas", "Karl Deutsch", "Jean Monnet"], 0, "Mitrany. Haas developed neo-functionalism (spillover)."),
  p2("x68", "International Relations", "Direct", "'Structural violence' and 'positive peace' are concepts of:",
    ["Johan Galtung", "Kenneth Boulding", "John Burton", "Anatol Rapoport"], 0, "Galtung, founder of peace research."),
  p2("x69", "International Relations", "Direct", "The 'security dilemma' was first formulated by:",
    ["John Herz", "Robert Jervis", "Kenneth Waltz", "Thomas Schelling"], 0, "Herz (1950). Jervis developed it later (1978)."),
  p2("x70", "International Relations", "Direct", "'Securitisation' theory is associated with:",
    ["Copenhagen School", "Frankfurt School", "English School", "Chicago School"], 0, "Buzan and Wæver."),
  p2("x71", "International Relations", "Direct", "'Theory is always for someone and for some purpose' was said by:",
    ["Robert Cox", "Andrew Linklater", "Richard Ashley", "Mark Hoffman"], 0, "Cox (1981), a critical/Gramscian IR theorist."),
  p2("x72", "International Relations", "Direct", "'Bananas, Beaches and Bases' (1989) is a feminist IR work by:",
    ["J. Ann Tickner", "Cynthia Enloe", "Christine Sylvester", "Jean Bethke Elshtain"], 1, "Enloe. Tickner wrote Gender in International Relations (1992)."),
  p2("x73", "International Relations", "Direct", "Hegemonic stability theory originated with:",
    ["Charles Kindleberger", "Immanuel Wallerstein", "Hedley Bull", "Andre Gunder Frank"], 0, "Kindleberger, The World in Depression (1973). Developed by Gilpin and Krasner."),
  p2("x74", "International Relations", "Chronology", "Arrange: A. NATO  B. Truman Doctrine  C. Warsaw Pact  D. Marshall Plan enacted",
    ["B, D, A, C", "D, B, A, C", "B, A, D, C", "B, D, C, A"], 0, "1947 → 1948 → 1949 → 1955."),
  p2("x75", "International Relations", "Direct", "The UN Charter was signed on 26 June 1945 at:",
    ["Dumbarton Oaks", "Yalta", "San Francisco", "London"], 2, "San Francisco. It came into force on 24 October 1945."),
  p2("x76", "International Relations", "Direct", "The veto power of the P5 flows from which Article of the UN Charter?",
    ["Article 2", "Article 27", "Article 51", "Article 99"], 1, "Article 27(3). Article 51 is self-defence and Article 99 the Secretary-General."),
  p2("x77", "International Relations", "Chronology", "Arrange: A. ASEAN  B. SAARC  C. SCO  D. European Coal and Steel Community",
    ["D, A, B, C", "A, D, B, C", "D, B, A, C", "D, A, C, B"], 0, "1951 → 1967 → 1985 → 2001."),
  p2("x78", "International Relations", "Direct", "The 'Democratic Peace' thesis in modern IR was revived by:",
    ["Michael Doyle", "John Mearsheimer", "Stephen Walt", "Robert Gilpin"], 0, "Doyle (1983), drawing on Kant's Perpetual Peace."),
  p2("x79", "International Relations", "Direct", "Which country was NOT among the new BRICS members of 2024?",
    ["Egypt", "Ethiopia", "Iran", "Argentina"], 3, "Argentina declined. Egypt, Ethiopia, Iran and the UAE joined in 2024, and Indonesia in 2025."),
  p2("x80", "International Relations", "Direct", "The 'Balance of Threat' theory was proposed by:",
    ["Stephen Walt", "Kenneth Waltz", "Randall Schweller", "Glenn Snyder"], 0, "Walt (1987). Watch the Walt/Waltz name trap."),
  p2("x81", "International Relations", "Direct", "The Bretton Woods conference (1944) created:",
    ["UN and WHO", "IMF and IBRD", "GATT and WTO", "IMF and WTO"], 1, "IMF and IBRD. GATT came in 1947 and the WTO in 1995."),
  p2("x82", "International Relations", "Direct", "The demand for a New International Economic Order (NIEO) was adopted by the UN General Assembly in:",
    ["1964", "1974", "1984", "1991"], 1, "1974, at the 6th Special Session."),

  // ---------- India's Foreign Policy ----------
  p2("x83", "India's Foreign Policy", "Direct", "The India–USSR Treaty of Peace, Friendship and Cooperation was signed in:",
    ["1955", "1966", "1971", "1975"], 2, "August 1971, before the Bangladesh war."),
  p2("x84", "India's Foreign Policy", "Direct", "India's first nuclear test, 'Smiling Buddha', took place in:",
    ["1964", "1974", "1988", "1998"], 1, "18 May 1974, Pokhran-I. Pokhran-II (Operation Shakti) was in 1998."),
  p2("x85", "India's Foreign Policy", "Direct", "The India–Bangladesh Land Boundary Agreement was implemented through the:",
    ["99th Amendment", "100th Amendment", "101st Amendment", "102nd Amendment"], 1, "100th Amendment (2015), which exchanged enclaves."),
  p2("x86", "India's Foreign Policy", "Direct", "The Indo-Sri Lanka Accord (1987) led to the deployment of:",
    ["UNIFIL", "IPKF", "SAARC force", "Operation Cactus"], 1, "IPKF. Operation Cactus (1988) was in the Maldives."),
  p2("x87", "India's Foreign Policy", "Direct", "The India–Nepal Treaty of Peace and Friendship was signed in:",
    ["1947", "1950", "1962", "1996"], 1, "1950. 1996 is the Mahakali Treaty."),
  p2("x88", "India's Foreign Policy", "Direct", "The 30-year Ganga Water Sharing Treaty with Bangladesh was signed in:",
    ["1977", "1985", "1996", "2011"], 2, "1996 (Deve Gowda and Sheikh Hasina). 1977 was the earlier Farakka agreement."),
  p2("x89", "India's Foreign Policy", "Direct", "I2U2 is a grouping of India with:",
    ["Iran, Iraq, US", "Israel, UAE, US", "Indonesia, UAE, UK", "Israel, UK, US"], 1, "Israel, UAE and US (2021–22)."),
  p2("x90", "India's Foreign Policy", "Direct", "India's 'Connect Central Asia' policy was announced in:",
    ["2004", "2012", "2016", "2020"], 1, "2012, at Bishkek."),
  p2("x91", "India's Foreign Policy", "Direct", "India–US civil nuclear cooperation was operationalised by the '123 Agreement' in:",
    ["2005", "2008", "2010", "2014"], 1, "2008 (announced July 2005). It came with an NSG waiver in 2008."),
  p2("x92", "India's Foreign Policy", "Direct", "India's nuclear doctrine with 'No First Use' was formally adopted in:",
    ["1974", "1998", "2003", "2008"], 2, "January 2003. The draft doctrine was from 1999."),
  p2("x93", "India's Foreign Policy", "Direct", "The India–Middle East–Europe Economic Corridor (IMEC) was announced at:",
    ["G20 New Delhi, 2023", "BRICS Johannesburg, 2023", "SCO Astana, 2024", "Quad Tokyo, 2022"], 0, "The G20 summit in New Delhi, September 2023."),
  p2("x94", "India's Foreign Policy", "Direct", "India and Pakistan became full members of the SCO in:",
    ["2001", "2015", "2017", "2019"], 2, "June 2017, at Astana."),

  // ---------- Political Institutions ----------
  p2("x95", "Political Institutions", "Direct", "Ambedkar called which Article the 'heart and soul' of the Constitution?",
    ["Article 14", "Article 19", "Article 21", "Article 32"], 3, "Article 32, the right to constitutional remedies."),
  p2("x96", "Political Institutions", "Direct", "Fundamental Duties were added on the recommendation of the:",
    ["Sarkaria Commission", "Swaran Singh Committee", "Verma Committee", "Venkatachaliah Commission"], 1, "Swaran Singh Committee; 42nd Amendment (1976), Article 51A."),
  p2("x97", "Political Institutions", "Direct", "A joint sitting of Parliament (Article 108) CANNOT be held for:",
    ["Ordinary bills", "Financial bills", "Money bills", "Bills passed by Lok Sabha"], 2, "Money bills and constitutional amendment bills are excluded."),
  p2("x98", "Political Institutions", "Direct", "Which emergency has never been proclaimed in India?",
    ["National emergency (Art 352)", "President's Rule (Art 356)", "Financial emergency (Art 360)", "None of these"], 2, "Article 360 has never been invoked."),
  p2("x99", "Political Institutions", "Direct", "New All India Services can be created after a resolution of:",
    ["Lok Sabha", "Rajya Sabha", "Inter-State Council", "Union Cabinet"], 1, "Article 312 requires a Rajya Sabha resolution passed by two-thirds."),
  p2("x100", "Political Institutions", "Direct", "Which amendment gave constitutional status to the National Commission for Backward Classes?",
    ["101st", "102nd", "103rd", "105th"], 1, "102nd (2018), Article 338B. The 105th (2021) restored states' power to list SEBCs."),
  p2("x101", "Political Institutions", "Direct", "Nomination of Anglo-Indians to Lok Sabha was ended by the:",
    ["103rd Amendment", "104th Amendment", "105th Amendment", "106th Amendment"], 1, "104th (2019, effective 2020), which also extended SC/ST reservation."),
  p2("x102", "Political Institutions", "Direct", "'Procedure established by law' must be fair, just and reasonable. This was held in:",
    ["A.K. Gopalan (1950)", "Maneka Gandhi (1978)", "ADM Jabalpur (1976)", "Kharak Singh (1962)"], 1, "Maneka Gandhi overruled the narrow reading in Gopalan."),
  p2("x103", "Political Institutions", "Direct", "Guidelines on sexual harassment at the workplace were laid down in:",
    ["Vishaka (1997)", "Shah Bano (1985)", "Shayara Bano (2017)", "Navtej Johar (2018)"], 0, "Vishaka v. State of Rajasthan. Shayara Bano was the triple talaq case."),
  p2("x104", "Political Institutions", "Direct", "The 50% ceiling on reservations and the 'creamy layer' exclusion were laid down in:",
    ["Champakam Dorairajan", "Indra Sawhney", "M. Nagaraj", "Janhit Abhiyan"], 1, "Indra Sawhney (1992). Janhit Abhiyan (2022) upheld EWS reservation."),
  p2("x105", "Political Institutions", "Direct", "S.R. Bommai (1994) is significant because it:",
    ["Upheld the 42nd Amendment", "Made the floor test the way to prove majority and limited Article 356", "Created the collegium", "Struck down NJAC"], 1, "It also declared secularism part of the basic structure."),
  p2("x106", "Political Institutions", "Direct", "The Inter-State Council under Article 263 was set up in 1990 on the recommendation of:",
    ["Rajamannar Committee", "Sarkaria Commission", "Punchhi Commission", "First ARC"], 1, "Sarkaria (1988 report)."),
  p2("x107", "Political Institutions", "Direct", "Zonal Councils in India are:",
    ["Constitutional bodies", "Statutory bodies under the States Reorganisation Act, 1956", "Executive bodies created by NITI Aayog", "Created by the 73rd Amendment"], 1, "Statutory bodies. The North Eastern Council came under a separate 1971 Act."),
  p2("x108", "Political Institutions", "Direct", "Who can take part in parliamentary proceedings but cannot vote?",
    ["Comptroller and Auditor General", "Attorney General", "Chief Election Commissioner", "Solicitor General"], 1, "The Attorney General (Article 88)."),
  p2("x109", "Political Institutions", "Chronology", "Arrange: A. Maneka Gandhi  B. A.K. Gopalan  C. Puttaswamy  D. Indra Sawhney",
    ["B, A, D, C", "A, B, D, C", "B, D, A, C", "B, A, C, D"], 0, "1950 → 1978 → 1992 → 2017."),
  p2("x110", "Political Institutions", "Direct", "'Constitutional morality' was first emphasised in the Constituent Assembly by Ambedkar, quoting:",
    ["A.V. Dicey", "George Grote", "Ivor Jennings", "Walter Bagehot"], 1, "Ambedkar quoted the historian George Grote (4 November 1948)."),

  // ---------- Political Processes ----------
  p2("x111", "Political Processes", "Direct", "The Mandal Commission report was submitted in 1980 and its recommendations were implemented in 1990 by the government of:",
    ["Rajiv Gandhi", "V.P. Singh", "Chandra Shekhar", "P.V. Narasimha Rao"], 1, "V.P. Singh, in August 1990."),
  p2("x112", "Political Processes", "Direct", "'India's Silent Revolution' (2003), on the rise of lower castes in north India, was written by:",
    ["Christophe Jaffrelot", "Paul Brass", "Atul Kohli", "Zoya Hasan"], 0, "Jaffrelot."),
  p2("x113", "Political Processes", "Direct", "'The Modernity of Tradition' (1967) was written by:",
    ["Lloyd and Susanne Rudolph", "Myron Weiner", "Rajni Kothari", "M.N. Srinivas"], 0, "The Rudolphs, who also wrote In Pursuit of Lakshmi (1987)."),
  p2("x114", "Political Processes", "Direct", "'Democracy and Discontent' (1990), on India's 'crisis of governability', was written by:",
    ["Atul Kohli", "Ashutosh Varshney", "Pratap Bhanu Mehta", "Partha Chatterjee"], 0, "Kohli."),
  p2("x115", "Political Processes", "Direct", "'Ethnic Conflict and Civic Life' (2002) explained Hindu–Muslim riots through civic networks. Its author is:",
    ["Ashutosh Varshney", "Paul Brass", "Steven Wilkinson", "Thomas Blom Hansen"], 0, "Varshney. Brass wrote of an 'institutionalised riot system'."),
  p2("x116", "Political Processes", "Direct", "'The Indian Constitution: Cornerstone of a Nation' (1966) was written by:",
    ["Granville Austin", "K.C. Wheare", "Ivor Jennings", "D.D. Basu"], 0, "Austin, who later wrote Working a Democratic Constitution (1999)."),
  p2("x117", "Political Processes", "Direct", "The Bahujan Samaj Party was founded in 1984 by:",
    ["B.R. Ambedkar", "Kanshi Ram", "Mayawati", "Jagjivan Ram"], 1, "Kanshi Ram, building on BAMCEF (1978) and DS4 (1981)."),
  p2("x118", "Political Processes", "Direct", "The Dalit Panthers (1972) emerged in:",
    ["Tamil Nadu", "Maharashtra", "Uttar Pradesh", "Punjab"], 1, "Maharashtra, inspired by the Black Panthers."),
  p2("x119", "Political Processes", "Direct", "The Narmada Bachao Andolan is most associated with:",
    ["Sunderlal Bahuguna", "Medha Patkar", "Chandi Prasad Bhatt", "Pandurang Hegde"], 1, "Patkar. Bahuguna and Bhatt led Chipko, and Hegde led Appiko."),
  p2("x120", "Political Processes", "Direct", "'Party Politics in India' (1957) was written by:",
    ["Myron Weiner", "W.H. Morris-Jones", "Rajni Kothari", "Stanley Kochanek"], 0, "Weiner."),
  p2("x121", "Political Processes", "Chronology", "Arrange: A. Mandal implementation  B. JP movement  C. First Janata government at the Centre  D. Anti-Hindi agitation in Madras",
    ["D, B, C, A", "B, D, C, A", "D, C, B, A", "D, B, A, C"], 0, "1965 → 1974 → 1977 → 1990."),
  p2("x122", "Political Processes", "Direct", "K.C. Wheare described the Indian Constitution as:",
    ["Federal", "Unitary", "Quasi-federal", "Confederal"], 2, "'Quasi-federal'. Ivor Jennings called it 'a federation with a strong centralising tendency'."),

  // ---------- Public Administration ----------
  p2("x123", "Public Administration", "Direct", "'The Study of Administration' (1887), proposing the politics–administration dichotomy, was written by:",
    ["Frank Goodnow", "Woodrow Wilson", "L.D. White", "W.F. Willoughby"], 1, "Wilson. Goodnow wrote Politics and Administration (1900)."),
  p2("x124", "Public Administration", "Direct", "The first textbook of public administration, 'Introduction to the Study of Public Administration' (1926), was written by:",
    ["L.D. White", "W.F. Willoughby", "Dwight Waldo", "Luther Gulick"], 0, "White (1926). Willoughby's Principles came in 1927."),
  p2("x125", "Public Administration", "Chronology", "Arrange: A. Administrative Behavior (Simon)  B. The Study of Administration (Wilson)  C. Principles of Scientific Management (Taylor)  D. General and Industrial Management (Fayol)",
    ["B, C, D, A", "C, B, D, A", "B, D, C, A", "B, C, A, D"], 0, "1887 → 1911 → 1916 → 1947."),
  p2("x126", "Public Administration", "Direct", "'Satisficing' instead of maximising was proposed by:",
    ["Herbert Simon", "Charles Lindblom", "Chester Barnard", "Amitai Etzioni"], 0, "Simon, under bounded rationality."),
  p2("x127", "Public Administration", "Direct", "According to Herzberg, salary is a:",
    ["Motivator", "Hygiene factor", "Self-actualisation need", "Esteem need"], 1, "Hygiene factor. Motivators include achievement, recognition and the work itself."),
  p2("x128", "Public Administration", "Chronology", "Arrange Maslow's needs from lowest: A. Esteem  B. Safety  C. Self-actualisation  D. Belongingness  E. Physiological",
    ["E, B, D, A, C", "E, D, B, A, C", "B, E, D, A, C", "E, B, A, D, C"], 0, "Physiological → Safety → Love/belonging → Esteem → Self-actualisation."),
  p2("x129", "Public Administration", "Direct", "'The Human Side of Enterprise' (1960), presenting Theory X and Theory Y, was written by:",
    ["Douglas McGregor", "Rensis Likert", "Chris Argyris", "Abraham Maslow"], 0, "McGregor."),
  p2("x130", "Public Administration", "Direct", "The 'immaturity–maturity' theory of personality in organisations is associated with:",
    ["Chris Argyris", "Frederick Herzberg", "Warren Bennis", "Rensis Likert"], 0, "Argyris, Personality and Organization (1957)."),
  p2("x131", "Public Administration", "Direct", "The 'law of the situation' and constructive conflict are associated with:",
    ["Mary Parker Follett", "Elton Mayo", "Chester Barnard", "Lyndall Urwick"], 0, "Follett: depersonalise orders through the law of the situation."),
  p2("x132", "Public Administration", "Direct", "Which is NOT one of Weber's ideal types of authority?",
    ["Traditional", "Charismatic", "Legal-rational", "Coercive"], 3, "Weber's three types are traditional, charismatic and legal-rational."),
  p2("x133", "Public Administration", "Direct", "The mathematical formula for span of control was given by:",
    ["V.A. Graicunas", "Luther Gulick", "Henri Fayol", "Lyndall Urwick"], 0, "Graicunas (1933): relationships grow exponentially with subordinates."),
  p2("x134", "Public Administration", "Direct", "Management by Objectives (MBO) was popularised by:",
    ["Peter Drucker", "Henri Fayol", "Herbert Simon", "Elton Mayo"], 0, "Drucker, The Practice of Management (1954)."),
  p2("x135", "Public Administration", "Direct", "'The Intellectual Crisis in American Public Administration' (1973), applying public choice theory, was written by:",
    ["Vincent Ostrom", "Dwight Waldo", "Frank Marini", "H. George Frederickson"], 0, "Ostrom. Marini edited the Minnowbrook I volume."),
  p2("x136", "Public Administration", "Direct", "'Administration in Developing Countries: The Theory of Prismatic Society' (1964) was written by:",
    ["Fred Riggs", "Ferrel Heady", "Edward Weidner", "Dwight Waldo"], 0, "Riggs. Weidner is linked with 'development administration' as a field."),
  p2("x137", "Public Administration", "Direct", "Paul Appleby submitted reports on Indian public administration in:",
    ["1950 and 1952", "1953 and 1956", "1960 and 1962", "1966 and 1970"], 1, "1953 (Public Administration in India: Report of a Survey) and 1956."),

  // ---------- Governance & Public Policy ----------
  p2("x138", "Governance & Policy", "Direct", "Public policy as 'whatever governments choose to do or not to do' was defined by:",
    ["Thomas Dye", "David Easton", "Harold Lasswell", "Carl Friedrich"], 0, "Dye, Understanding Public Policy."),
  p2("x139", "Governance & Policy", "Direct", "The 'garbage can model' of organisational choice (1972) was given by:",
    ["Cohen, March and Olsen", "Lindblom and Braybrooke", "Kingdon", "Sabatier and Jenkins-Smith"], 0, "Cohen, March and Olsen. Kingdon's 'multiple streams' adapted it."),
  p2("x140", "Governance & Policy", "Direct", "'Mixed scanning' as a decision-making model was proposed by:",
    ["Amitai Etzioni", "Yehezkel Dror", "Charles Lindblom", "Herbert Simon"], 0, "Etzioni (1967), a middle path between rational and incremental models."),
  p2("x141", "Governance & Policy", "Direct", "The 'multiple streams' framework (problems, policies, politics) is associated with:",
    ["John Kingdon", "Paul Sabatier", "Theodore Lowi", "Aaron Wildavsky"], 0, "Kingdon, Agendas, Alternatives, and Public Policies (1984)."),
  p2("x142", "Governance & Policy", "Direct", "The Citizen's Charter as an administrative reform began in 1991 in:",
    ["USA", "UK", "Canada", "Australia"], 1, "The UK, under John Major. India adopted it in 1997."),
  p2("x143", "Governance & Policy", "Direct", "The Central Vigilance Commission (1964) was set up on the recommendation of the:",
    ["Santhanam Committee", "Kripalani Committee", "First ARC", "Gorwala Report"], 0, "Santhanam Committee on Prevention of Corruption (1962–64)."),
  p2("x144", "Governance & Policy", "Direct", "NITI Aayog replaced the Planning Commission on:",
    ["15 August 2014", "1 January 2015", "26 January 2015", "1 April 2015"], 1, "1 January 2015. The Planning Commission was set up in March 1950."),
  p2("x145", "Governance & Policy", "Direct", "The State Finance Commission for panchayats is provided under:",
    ["Article 243G", "Article 243I", "Article 243K", "Article 280"], 1, "243I (every 5 years). 243K is the State Election Commission."),
  p2("x146", "Governance & Policy", "Direct", "The term 'governance' entered development discourse prominently through a 1989 World Bank report on:",
    ["Latin America", "Sub-Saharan Africa", "South Asia", "East Asia"], 1, "'Sub-Saharan Africa: From Crisis to Sustainable Growth' (1989)."),
  p2("x147", "Governance & Policy", "Direct", "India's first Lokpal chairperson (2019) was:",
    ["Justice P.C. Ghose", "Justice J.S. Verma", "Justice A.M. Khanwilkar", "Justice R.M. Lodha"], 0, "Justice Pinaki Chandra Ghose. Khanwilkar became Lokpal in 2024."),
  p2("x148", "Governance & Policy", "Direct", "Social audit in India was pioneered at the grassroots by:",
    ["SEWA", "Mazdoor Kisan Shakti Sangathan (MKSS)", "PRADAN", "Chipko activists"], 1, "MKSS in Rajasthan (jan sunwais). Social audit was later made mandatory under MGNREGA."),
  p2("x149", "Governance & Policy", "Direct", "The National e-Governance Plan (NeGP) was approved in:",
    ["2000", "2006", "2015", "2019"], 1, "2006. Digital India came in 2015."),
  p2("x150", "Governance & Policy", "Direct", "The 'policy sciences' orientation (1951) was proposed by:",
    ["Harold Lasswell", "Yehezkel Dror", "Thomas Dye", "Charles Lindblom"], 0, "Lasswell and Lerner, The Policy Sciences (1951)."),
];

export const morePaper1: MCQ[] = [
  // Teaching Aptitude
  q("n1", 1, "Teaching Aptitude", "Chronology", "Arrange Herbart's steps of teaching: A. Association  B. Preparation  C. Application  D. Presentation  E. Generalisation",
    ["B, D, A, E, C", "D, B, A, E, C", "B, D, E, A, C", "B, A, D, E, C"], 0, "Preparation → Presentation → Association → Generalisation → Application."),
  q("n2", 1, "Teaching Aptitude", "Direct", "The 'reflective level' of teaching was proposed by:",
    ["Herbart", "Morrison", "Hunt", "Bloom"], 2, "Memory level is Herbart, understanding level Morrison and reflective level Hunt (Bigge & Hunt)."),
  q("n3", 1, "Teaching Aptitude", "Direct", "Micro-teaching originated at:",
    ["Harvard University", "Stanford University", "Columbia University", "Oxford University"], 1, "Stanford (Dwight Allen and colleagues, early 1960s)."),
  q("n4", 1, "Teaching Aptitude", "Direct", "Flanders' Interaction Analysis System has how many categories?",
    ["7", "10", "12", "15"], 1, "10 categories: teacher talk 1–7, student talk 8–9 and silence/confusion 10."),
  q("n5", 1, "Teaching Aptitude", "Direct", "The 'Zone of Proximal Development' was proposed by:",
    ["Piaget", "Vygotsky", "Bruner", "Ausubel"], 1, "Vygotsky. Scaffolding was later coined by Wood, Bruner & Ross."),
  q("n6", 1, "Teaching Aptitude", "Direct", "'Advance organisers' are associated with:",
    ["David Ausubel", "Jerome Bruner", "Robert Gagné", "B.F. Skinner"], 0, "Ausubel's meaningful reception learning. Bruner is linked to discovery learning."),
  q("n7", 1, "Teaching Aptitude", "Chronology", "Arrange Piaget's stages: A. Formal operational  B. Pre-operational  C. Sensorimotor  D. Concrete operational",
    ["C, B, D, A", "B, C, D, A", "C, D, B, A", "C, B, A, D"], 0, "Sensorimotor (0–2) → Pre-operational (2–7) → Concrete (7–11) → Formal (11+)."),
  q("n8", 1, "Teaching Aptitude", "Direct", "The theory of Multiple Intelligences (1983) was given by:",
    ["Howard Gardner", "Daniel Goleman", "Robert Sternberg", "Alfred Binet"], 0, "Gardner. Goleman: emotional intelligence. Sternberg: triarchic theory."),
  q("n9", 1, "Teaching Aptitude", "Direct", "A test that compares a student's performance with that of other students is:",
    ["Criterion-referenced", "Norm-referenced", "Diagnostic", "Formative"], 1, "Norm-referenced. Criterion-referenced compares with a fixed standard."),
  q("n10", 1, "Teaching Aptitude", "Direct", "The Choice Based Credit System (CBCS) was introduced in Indian universities by UGC in:",
    ["2010", "2015", "2018", "2020"], 1, "2015–16."),
  // Research Aptitude
  q("n11", 1, "Research Aptitude", "Direct", "Research that studies causes after the effect has already occurred, without manipulating variables, is:",
    ["Experimental", "Ex post facto", "Action research", "Longitudinal"], 1, "Ex post facto (causal-comparative)."),
  q("n12", 1, "Research Aptitude", "Direct", "The best sampling method for a hidden population (e.g., drug users) is:",
    ["Simple random", "Stratified", "Snowball", "Systematic"], 2, "Snowball: participants refer other participants."),
  q("n13", 1, "Research Aptitude", "Direct", "Which of these is a non-parametric test?",
    ["t-test", "ANOVA", "Chi-square", "Pearson's r"], 2, "Chi-square. The others assume parameters such as normality."),
  q("n14", 1, "Research Aptitude", "Direct", "'Shodhganga', a repository of Indian theses, is maintained by:",
    ["NAAC", "INFLIBNET", "ICSSR", "NIRF"], 1, "INFLIBNET (Gandhinagar)."),
  q("n15", 1, "Research Aptitude", "Direct", "'Ibid.' in a reference means:",
    ["In the work already cited", "The same source as the immediately preceding note", "And others", "Compare"], 1, "'Op. cit.' means the work already cited. 'Et al.' means and others. 'Cf.' means compare."),
  q("n16", 1, "Research Aptitude", "Direct", "The h-index for measuring research impact was proposed by:",
    ["Eugene Garfield", "Jorge Hirsch", "Derek de Solla Price", "Alfred Lotka"], 1, "Hirsch (2005). Garfield created the Impact Factor."),
  q("n17", 1, "Research Aptitude", "Direct", "A Likert scale is primarily used to measure:",
    ["Intelligence", "Attitudes", "Reaction time", "Height"], 1, "Attitudes, through agreement levels."),
  // Communication
  q("n18", 1, "Communication", "Direct", "'The medium is the message' was said by:",
    ["Marshall McLuhan", "Harold Lasswell", "Wilbur Schramm", "Claude Shannon"], 0, "McLuhan, Understanding Media (1964)."),
  q("n19", 1, "Communication", "Direct", "'Who says what, in which channel, to whom, with what effect' is the model of:",
    ["Shannon and Weaver", "Lasswell", "Berlo", "Osgood and Schramm"], 1, "Lasswell (1948). Shannon–Weaver (1949) introduced noise."),
  q("n20", 1, "Communication", "Direct", "Informal communication in an organisation is called:",
    ["Chain of command", "Grapevine", "Downward communication", "Formal network"], 1, "Grapevine."),
  q("n21", 1, "Communication", "Direct", "The SMCR model of communication was given by:",
    ["David Berlo", "Aristotle", "Lasswell", "Newcomb"], 0, "Berlo (1960): Source, Message, Channel, Receiver."),
  // Reasoning / Maths
  q("n22", 1, "Logical Reasoning", "Direct", "Statements: All A are B. Some B are C. Conclusion: Some A are C. This conclusion:",
    ["Definitely follows", "Does not necessarily follow", "Is false", "Is a contradiction"], 1, "The 'some B' that are C may not include any A."),
  q("n23", 1, "Logical Reasoning", "Direct", "In Indian logic, 'Arthapatti' means:",
    ["Perception", "Postulation (presumption)", "Comparison", "Non-cognition"], 1, "The classic example: fat Devadatta does not eat by day, so he eats at night."),
  q("n24", 1, "Logical Reasoning", "Direct", "'Anupalabdhi' as a pramana is accepted by:",
    ["Nyaya", "Bhatta Mimamsa and Advaita Vedanta", "Charvaka", "Buddhism"], 1, "Non-cognition, used to know absence."),
  q("n25", 1, "Logical Reasoning", "Direct", "Book : Author :: Painting : ?",
    ["Canvas", "Painter", "Gallery", "Colour"], 1, "Creator relationship."),
  q("n26", 1, "Mathematical Reasoning", "Direct", "Next term: 3, 9, 27, 81, ?",
    ["162", "216", "243", "324"], 2, "×3 each time."),
  q("n27", 1, "Mathematical Reasoning", "Direct", "20% of 30% of 500 is:",
    ["30", "50", "60", "150"], 0, "30% of 500 = 150, and 20% of 150 = 30."),
  q("n28", 1, "Mathematical Reasoning", "Direct", "Simple interest on ₹5000 at 10% per annum for 2 years is:",
    ["₹500", "₹1000", "₹1050", "₹1100"], 1, "5000 × 10 × 2 / 100 = 1000. Compound interest would be ₹1050, which is the trap."),
  q("n29", 1, "Mathematical Reasoning", "Direct", "A car goes a distance at 60 km/h and returns at 40 km/h. Its average speed is:",
    ["50 km/h", "48 km/h", "45 km/h", "52 km/h"], 1, "2 × 60 × 40 / (60 + 40) = 48. It is not the simple average."),
  q("n30", 1, "Mathematical Reasoning", "Direct", "The mean of the first 10 natural numbers is:",
    ["5", "5.5", "6", "10"], 1, "55 / 10 = 5.5."),
  q("n31", 1, "Mathematical Reasoning", "Direct", "If CAT = 24 (letter positions added), then DOG = ?",
    ["24", "26", "27", "30"], 1, "4 + 15 + 7 = 26."),
  // ICT
  q("n32", 1, "ICT", "Direct", "An IPv6 address is how many bits long?",
    ["32", "64", "128", "256"], 2, "128. IPv4 is 32."),
  q("n33", 1, "ICT", "Direct", "Which memory is volatile?",
    ["ROM", "RAM", "Hard disk", "Flash drive"], 1, "RAM loses its data without power."),
  q("n34", 1, "ICT", "Direct", "1 byte equals:",
    ["4 bits", "8 bits", "16 bits", "1024 bits"], 1, "8 bits."),
  q("n35", 1, "ICT", "Direct", "Malware that encrypts files and demands payment is:",
    ["Spyware", "Ransomware", "Adware", "Worm"], 1, "Ransomware."),
  // Environment
  q("n36", 1, "Environment", "Chronology", "Arrange: A. Paris Agreement  B. Kyoto Protocol  C. Montreal Protocol  D. Ramsar Convention",
    ["D, C, B, A", "C, D, B, A", "D, B, C, A", "D, C, A, B"], 0, "1971 → 1987 → 1997 → 2015."),
  q("n37", 1, "Environment", "Direct", "Minamata disease is caused by:",
    ["Cadmium", "Mercury", "Lead", "Arsenic"], 1, "Mercury. Itai-itai disease is cadmium."),
  q("n38", 1, "Environment", "Direct", "'Blue baby syndrome' is caused by excess of which in drinking water?",
    ["Fluoride", "Nitrate", "Arsenic", "Iron"], 1, "Nitrate (methemoglobinemia)."),
  q("n39", 1, "Environment", "Direct", "The gas that leaked in the Bhopal disaster (1984) was:",
    ["Phosgene", "Methyl isocyanate", "Chlorine", "Hydrogen sulphide"], 1, "Methyl isocyanate (MIC)."),
  q("n40", 1, "Environment", "Direct", "The Sendai Framework (2015–2030) deals with:",
    ["Climate finance", "Disaster risk reduction", "Biodiversity", "Ozone"], 1, "Disaster risk reduction. It succeeded the Hyogo Framework."),
  q("n41", 1, "Environment", "Direct", "The National Green Tribunal was established in:",
    ["1986", "2002", "2010", "2016"], 2, "2010 (NGT Act). 1986 is the Environment Protection Act."),
  // Higher Education
  q("n42", 1, "Higher Education", "Direct", "Which document is called the 'Magna Carta of English education in India'?",
    ["Macaulay's Minute (1835)", "Wood's Despatch (1854)", "Hunter Commission (1882)", "Sargent Plan (1944)"], 1, "Wood's Despatch, 1854."),
  q("n43", 1, "Higher Education", "Direct", "The NEP 2020 drafting committee was chaired by:",
    ["T.S.R. Subramanian", "K. Kasturirangan", "Yash Pal", "Sam Pitroda"], 1, "Kasturirangan. T.S.R. Subramanian chaired the 2016 committee, and Yash Pal the 2009 one."),
  q("n44", 1, "Higher Education", "Direct", "The Hunter Commission (1882) mainly focused on:",
    ["University education", "Primary and secondary education", "Technical education", "Women's education only"], 1, "Primary (and secondary) education."),
  q("n45", 1, "Higher Education", "Direct", "Rashtriya Uchchatar Shiksha Abhiyan (RUSA) was launched in:",
    ["2008", "2013", "2017", "2020"], 1, "2013, a centrally sponsored scheme for state universities."),
];
