export type Source = {
  // "pyq": stem and answer confirmed from a past-paper source.
  // "topic": topic confirmed asked in a past paper; wording rebuilt.
  kind: "pyq" | "topic";
  label: string;
  url: string;
};

export type MCQ = {
  id: string;
  source?: Source;
  paper: 1 | 2;
  unit: string;
  format: "Direct" | "Match" | "Chronology" | "Statements" | "Assertion-Reason";
  question: string;
  options: [string, string, string, string];
  answer: 0 | 1 | 2 | 3;
  explain: string;
};

export const paper2Bank: MCQ[] = [
  // Political Theory
  {
    id: "pt1", paper: 2, unit: "Political Theory", format: "Direct",
    source: { kind: "topic", label: "Dec 2024 cycle: Easton's definition", url: "https://www.oliveboard.in/blog/ugc-net-political-science-exam-analysis-2024-6-jan-2025/" },
    question: "Politics as the 'authoritative allocation of values for a society' was defined by:",
    options: ["Harold Lasswell", "David Easton", "Robert Dahl", "Gabriel Almond"],
    answer: 1,
    explain: "Easton (The Political System, 1953). Trap: Lasswell's definition is 'who gets what, when, how'.",
  },
  {
    id: "pt2", paper: 2, unit: "Political Theory", format: "Direct",
    question: "'Politics: Who Gets What, When, How' (1936) was written by:",
    options: ["Harold Lasswell", "Charles Merriam", "David Easton", "Robert Dahl"],
    answer: 0,
    explain: "Harold Lasswell. Easton's is the 'authoritative allocation of values'.",
  },
  {
    id: "pt3", paper: 2, unit: "Political Theory", format: "Direct",
    question: "The distinction between 'negative' and 'positive' liberty was famously drawn in 'Two Concepts of Liberty' by:",
    options: ["J.S. Mill", "T.H. Green", "Isaiah Berlin", "Quentin Skinner"],
    answer: 2,
    explain: "Isaiah Berlin (1958). Green defended positive liberty, and Skinner argued for republican liberty.",
  },
  {
    id: "pt4", paper: 2, unit: "Political Theory", format: "Statements",
    question:
      "Which of the following belong to John Rawls? A. Original position  B. Entitlement theory  C. Difference principle  D. Veil of ignorance  E. Minimal state",
    options: ["A, B and C only", "A, C and D only", "B, D and E only", "C, D and E only"],
    answer: 1,
    explain: "B and E are Nozick. Knowing just those two eliminates every other option.",
  },
  {
    id: "pt5", paper: 2, unit: "Political Theory", format: "Match",
    question:
      "Match: A. Michael Walzer  B. Robert Nozick  C. Amartya Sen  D. Michael Sandel — I. Anarchy, State and Utopia  II. Liberalism and the Limits of Justice  III. Spheres of Justice  IV. The Idea of Justice",
    options: ["A-III, B-I, C-IV, D-II", "A-I, B-III, C-II, D-IV", "A-III, B-IV, C-I, D-II", "A-II, B-I, C-IV, D-III"],
    answer: 0,
    explain: "Walzer: Spheres of Justice (1983); Nozick: ASU (1974); Sen: Idea of Justice (2009); Sandel: Limits of Justice (1982).",
  },
  {
    id: "pt6", paper: 2, unit: "Political Theory", format: "Direct",
    question: "'Iron Law of Oligarchy' is associated with:",
    options: ["Vilfredo Pareto", "Gaetano Mosca", "Robert Michels", "C. Wright Mills"],
    answer: 2,
    explain: "Michels (Political Parties, 1911). Pareto: circulation of elites. Mosca: ruling class. Mills: power elite.",
  },
  {
    id: "pt7", paper: 2, unit: "Political Theory", format: "Direct",
    question: "'Property is theft' is a statement of:",
    options: ["Karl Marx", "P.J. Proudhon", "Mikhail Bakunin", "Peter Kropotkin"],
    answer: 1,
    explain: "Proudhon, What is Property? (1840). All four are from the socialist/anarchist family, which is the distractor pattern.",
  },
  {
    id: "pt8", paper: 2, unit: "Political Theory", format: "Direct",
    question: "The concept of 'intersectionality' was coined by:",
    options: ["bell hooks", "Kimberlé Crenshaw", "Judith Butler", "Nancy Fraser"],
    answer: 1,
    explain: "Crenshaw (1989). Fraser: redistribution vs recognition. Butler: gender performativity.",
  },
  {
    id: "pt9", paper: 2, unit: "Political Theory", format: "Direct",
    question: "'The Sexual Contract' (1988) was written by:",
    options: ["Carole Pateman", "Susan Moller Okin", "Kate Millett", "Iris Marion Young"],
    answer: 0,
    explain: "Pateman argues the social contract rests on a prior sexual contract. Millett wrote Sexual Politics.",
  },
  {
    id: "pt10", paper: 2, unit: "Political Theory", format: "Assertion-Reason",
    question:
      "A: For Gramsci, the ruling class maintains power mainly through consent. R: Hegemony operates through civil society institutions such as schools, church and media.",
    options: ["Both true, R explains A", "Both true, R does not explain A", "A true, R false", "A false, R true"],
    answer: 0,
    explain: "Consent is manufactured through civil society, so R explains A.",
  },
  // Western Political Thought
  {
    id: "wt1", paper: 2, unit: "Western Thought", format: "Chronology",
    question: "Arrange by year of publication: A. Leviathan  B. The Prince  C. The Social Contract  D. Two Treatises of Government",
    options: ["B, A, D, C", "A, B, D, C", "B, D, A, C", "B, A, C, D"],
    answer: 0,
    explain: "Prince (written 1513) → Leviathan 1651 → Two Treatises 1689 → Social Contract 1762.",
  },
  {
    id: "wt2", paper: 2, unit: "Western Thought", format: "Direct",
    question: "'Man is born free, and everywhere he is in chains' opens:",
    options: ["Leviathan", "Two Treatises of Government", "The Social Contract", "Emile"],
    answer: 2,
    explain: "Rousseau, The Social Contract (1762).",
  },
  {
    id: "wt3", paper: 2, unit: "Western Thought", format: "Direct",
    question: "According to Aristotle, the perverted form of 'Polity' is:",
    options: ["Tyranny", "Oligarchy", "Democracy", "Anarchy"],
    answer: 2,
    explain: "Monarchy→Tyranny, Aristocracy→Oligarchy, Polity→Democracy.",
  },
  {
    id: "wt4", paper: 2, unit: "Western Thought", format: "Direct",
    question: "In Plato's Republic, the 'auxiliary' class corresponds to which element of the soul?",
    options: ["Reason", "Spirit", "Appetite", "Wisdom"],
    answer: 1,
    explain: "Rulers → reason, auxiliaries → spirit (courage), producers → appetite.",
  },
  {
    id: "wt5", paper: 2, unit: "Western Thought", format: "Match",
    source: { kind: "pyq", label: "Older PYQ (Testbook)", url: "https://testbook.com/question-answer/match-list-i-with-list-iilist-i--62207b5bbacbffc31d27a7de" },
    question:
      "Match: A. Marx  B. Lenin  C. Gramsci  D. Togliatti — I. Hegemony  II. Dictatorship of the proletariat  III. Polycentrism  IV. Vanguard party",
    options: ["A-II, B-IV, C-I, D-III", "A-IV, B-II, C-III, D-I", "A-II, B-I, C-IV, D-III", "A-I, B-IV, C-II, D-III"],
    answer: 0,
    explain: "Marx-II and Gramsci-I alone lock the answer. You don't need to know Togliatti.",
  },
  {
    id: "wt6", paper: 2, unit: "Western Thought", format: "Direct",
    question: "Qualitative distinction among pleasures ('better to be Socrates dissatisfied…') is associated with:",
    options: ["Jeremy Bentham", "J.S. Mill", "James Mill", "Henry Sidgwick"],
    answer: 1,
    explain: "J.S. Mill (Utilitarianism, 1863). Bentham's utilitarianism is quantitative (felicific calculus).",
  },
  {
    id: "wt7", paper: 2, unit: "Western Thought", format: "Direct",
    question: "'Vita activa' comprising labour, work and action is discussed in:",
    options: ["The Origins of Totalitarianism", "The Human Condition", "On Revolution", "Eichmann in Jerusalem"],
    answer: 1,
    explain: "Arendt, The Human Condition (1958).",
  },
  {
    id: "wt8", paper: 2, unit: "Western Thought", format: "Direct",
    question: "'Permanent Revolution' is associated with:",
    options: ["Stalin", "Lenin", "Trotsky", "Rosa Luxemburg"],
    answer: 2,
    explain: "Trotsky. Trap: Stalin's 'Socialism in One Country' is the opposing thesis.",
  },
  {
    id: "wt9", paper: 2, unit: "Western Thought", format: "Direct",
    question: "Which thinker regarded the state as 'the march of God on earth'?",
    options: ["Hegel", "Kant", "Green", "Bosanquet"],
    answer: 0,
    explain: "Hegel (Philosophy of Right, 1820).",
  },
  // Indian Political Thought
  {
    id: "ip1", paper: 2, unit: "Indian Thought", format: "Chronology",
    question:
      "Arrange by publication: A. Hind Swaraj  B. Annihilation of Caste  C. Gulamgiri  D. Integral Humanism",
    options: ["C, A, B, D", "A, C, B, D", "C, B, A, D", "C, A, D, B"],
    answer: 0,
    explain: "Gulamgiri 1873 → Hind Swaraj 1909 → Annihilation of Caste 1936 → Integral Humanism 1965.",
  },
  {
    id: "ip2", paper: 2, unit: "Indian Thought", format: "Direct",
    source: { kind: "pyq", label: "PYQ (Testbook): not part of Saptanga", url: "https://testbook.com/question-answer/which-one-of-the-following-was-not-a-part-of-kauti--625fdc2c926b1b5f6da44d94" },
    question: "Which is NOT one of Kautilya's seven elements (Saptanga) of the state?",
    options: ["Amatya", "Durga", "Purohita", "Mitra"],
    answer: 2,
    explain: "Swami, Amatya, Janapada, Durga, Kosha, Danda, Mitra. Purohita is not among them.",
  },
  {
    id: "ip3", paper: 2, unit: "Indian Thought", format: "Direct",
    question: "'The High-Caste Hindu Woman' (1887) was written by:",
    options: ["Savitribai Phule", "Tarabai Shinde", "Pandita Ramabai", "Sarojini Naidu"],
    answer: 2,
    explain: "Pandita Ramabai. Tarabai Shinde wrote Stri Purush Tulana (1882), which is a close distractor.",
  },
  {
    id: "ip4", paper: 2, unit: "Indian Thought", format: "Direct",
    question: "The 'Chaukhamba Raj' (Four-Pillar State) was proposed by:",
    options: ["J.P. Narayan", "Ram Manohar Lohia", "M.N. Roy", "Vinoba Bhave"],
    answer: 1,
    explain: "Lohia: village, district, province, centre.",
  },
  {
    id: "ip5", paper: 2, unit: "Indian Thought", format: "Direct",
    question: "The Self-Respect Movement (1925) was launched by:",
    options: ["B.R. Ambedkar", "E.V. Ramasamy 'Periyar'", "Jyotiba Phule", "Narayana Guru"],
    answer: 1,
    explain: "Periyar, in Tamil Nadu.",
  },
  {
    id: "ip6", paper: 2, unit: "Indian Thought", format: "Match",
    question:
      "Match: A. M.N. Roy  B. J.P. Narayan  C. Gandhi  D. Deendayal Upadhyaya — I. Trusteeship  II. Integral Humanism  III. Radical Humanism  IV. Total Revolution",
    options: ["A-III, B-IV, C-I, D-II", "A-IV, B-III, C-I, D-II", "A-III, B-I, C-IV, D-II", "A-II, B-IV, C-I, D-III"],
    answer: 0,
    explain: "Roy: Radical/New Humanism. JP: Total Revolution (1974). Gandhi: Trusteeship. Upadhyaya: Integral Humanism.",
  },
  {
    id: "ip7", paper: 2, unit: "Indian Thought", format: "Direct",
    question: "Kautilya's 'Mandala' theory relates to:",
    options: ["Local self-government", "Inter-state relations", "Taxation", "Caste order"],
    answer: 1,
    explain: "A circle of states: the immediate neighbour is a natural enemy, and the neighbour's neighbour is a natural ally.",
  },
  // Comparative Politics
  {
    id: "cp1", paper: 2, unit: "Comparative Politics", format: "Match",
    question:
      "Match approach with scholar: A. Systems analysis  B. Structural-functional  C. Communication theory  D. Consociational democracy — I. Karl Deutsch  II. Arend Lijphart  III. David Easton  IV. Gabriel Almond",
    options: ["A-III, B-IV, C-I, D-II", "A-IV, B-III, C-I, D-II", "A-III, B-IV, C-II, D-I", "A-I, B-IV, C-III, D-II"],
    answer: 0,
    explain: "Easton, Almond, Deutsch (The Nerves of Government), Lijphart.",
  },
  {
    id: "cp2", paper: 2, unit: "Comparative Politics", format: "Direct",
    question: "'Polarised pluralism' as a type of party system was described by:",
    options: ["Maurice Duverger", "Giovanni Sartori", "Jean Blondel", "Seymour Lipset"],
    answer: 1,
    explain: "Sartori, Parties and Party Systems (1976).",
  },
  {
    id: "cp3", paper: 2, unit: "Comparative Politics", format: "Direct",
    question: "Huntington's 'Third Wave' of democratisation began in 1974 with:",
    options: ["Spain", "Greece", "Portugal", "Argentina"],
    answer: 2,
    explain: "The Carnation Revolution in Portugal (April 1974). Spain followed in 1975.",
  },
  {
    id: "cp4", paper: 2, unit: "Comparative Politics", format: "Direct",
    question: "'The Civic Culture' (1963) classified political cultures as parochial, subject and participant. Its authors are:",
    options: ["Almond & Powell", "Almond & Verba", "Lipset & Rokkan", "Pye & Verba"],
    answer: 1,
    explain: "Almond & Verba. Almond & Powell wrote Comparative Politics: A Developmental Approach.",
  },
  {
    id: "cp5", paper: 2, unit: "Comparative Politics", format: "Direct",
    source: { kind: "pyq", label: "Jan 2026 paper (memory-based)", url: "https://www.adda247.com/jobs/wp-content/uploads/sites/13/2026/01/07180604/MEMORY-BASED-QUESTIONS-OF-UGC-NET-Political-Science-06-JAN-2026-SHIFT-1.pdf" },
    question: "Which Article of the US Constitution deals with the judiciary?",
    options: ["Article I", "Article II", "Article III", "Article IV"],
    answer: 2,
    explain: "I: legislature, II: executive, III: judiciary. This was asked in the Jan 2026 paper.",
  },
  {
    id: "cp6", paper: 2, unit: "Comparative Politics", format: "Statements",
    question:
      "About Duverger's law: A. Plurality single-member systems favour a two-party system. B. Proportional representation favours multi-partism. C. It was proposed by Sartori. D. It combines a 'mechanical' and a 'psychological' effect.",
    options: ["A and C only", "A, B and D only", "B, C and D only", "A, B, C and D"],
    answer: 1,
    explain: "C is false because it is Duverger's own law. Any option containing C goes.",
  },
  // International Relations
  {
    id: "ir1", paper: 2, unit: "International Relations", format: "Chronology",
    source: { kind: "topic", label: "Dec 2024 cycle: Westphalia chronology", url: "https://www.oliveboard.in/blog/ugc-net-political-science-exam-analysis-2024-6-jan-2025/" },
    question: "Arrange: A. Congress of Vienna  B. Peace of Westphalia  C. UN Charter  D. Treaty of Versailles",
    options: ["B, A, D, C", "A, B, D, C", "B, D, A, C", "B, A, C, D"],
    answer: 0,
    explain: "1648 → 1815 → 1919 → 1945.",
  },
  {
    id: "ir2", paper: 2, unit: "International Relations", format: "Match",
    question:
      "Match: A. Hans Morgenthau  B. Kenneth Waltz  C. John Mearsheimer  D. Alexander Wendt — I. Theory of International Politics  II. Politics Among Nations  III. Social Theory of International Politics  IV. The Tragedy of Great Power Politics",
    options: ["A-II, B-I, C-IV, D-III", "A-I, B-II, C-IV, D-III", "A-II, B-I, C-III, D-IV", "A-II, B-IV, C-I, D-III"],
    answer: 0,
    explain: "1948, 1979, 2001, 1999.",
  },
  {
    id: "ir3", paper: 2, unit: "International Relations", format: "Chronology",
    source: { kind: "topic", label: "Dec 2024 cycle: UN environment conferences", url: "https://www.oliveboard.in/blog/ugc-net-political-science-exam-analysis-2024-6-jan-2025/" },
    question: "Arrange UN environment conferences: A. Rio Earth Summit  B. Stockholm Conference  C. Rio+20  D. Johannesburg Summit",
    options: ["B, A, D, C", "A, B, D, C", "B, D, A, C", "B, A, C, D"],
    answer: 0,
    explain: "1972 → 1992 → 2002 → 2012. The Dec 2024 cycle asked this kind of question.",
  },
  {
    id: "ir4", paper: 2, unit: "International Relations", format: "Direct",
    question: "'Complex interdependence' is associated with:",
    options: ["Waltz", "Keohane & Nye", "Bull & Watson", "Farrell & Newman"],
    answer: 1,
    explain: "Power and Interdependence (1977). Farrell & Newman: weaponised interdependence.",
  },
  {
    id: "ir5", paper: 2, unit: "International Relations", format: "Direct",
    source: { kind: "topic", label: "June 2026 paper: Bentham / origin of IR", url: "https://www.pw.live/ugc-net/exams/ugc-net-june-2026-political-science-question-paper" },
    question: "The word 'international' was coined by:",
    options: ["Hugo Grotius", "Jeremy Bentham", "Immanuel Kant", "Woodrow Wilson"],
    answer: 1,
    explain: "Bentham (1780s). This kind of origin question appeared in June 2026.",
  },
  {
    id: "ir6", paper: 2, unit: "International Relations", format: "Assertion-Reason",
    question:
      "A: Morgenthau holds that states pursue national interest defined in terms of power. R: Politics is governed by objective laws rooted in human nature.",
    options: ["Both true, R explains A", "Both true, R does not explain A", "A true, R false", "A false, R true"],
    answer: 0,
    explain: "These are Morgenthau's 2nd and 1st principles. Power-seeking follows from human nature.",
  },
  {
    id: "ir7", paper: 2, unit: "International Relations", format: "Direct",
    question: "The 'English School' of IR is most associated with:",
    options: ["Hedley Bull", "Robert Cox", "Robert Gilpin", "J. Ann Tickner"],
    answer: 0,
    explain: "Bull, The Anarchical Society (1977). Cox: critical theory. Tickner: feminist IR.",
  },
  {
    id: "ir8", paper: 2, unit: "International Relations", format: "Chronology",
    question: "Arrange NATO accessions: A. Finland  B. West Germany  C. Sweden  D. Spain",
    options: ["B, D, A, C", "D, B, A, C", "B, D, C, A", "B, A, D, C"],
    answer: 0,
    explain: "West Germany 1955 → Spain 1982 → Finland 2023 → Sweden 2024.",
  },
  // India's Foreign Policy
  {
    id: "fp1", paper: 2, unit: "India's Foreign Policy", format: "Chronology",
    question: "Arrange: A. Act East Policy  B. Look East Policy  C. Gujral Doctrine  D. SAGAR",
    options: ["B, C, A, D", "C, B, A, D", "B, A, C, D", "B, C, D, A"],
    answer: 0,
    explain: "1991 → 1996 → 2014 → 2015.",
  },
  {
    id: "fp2", paper: 2, unit: "India's Foreign Policy", format: "Direct",
    question: "The first NAM summit was held in 1961 at:",
    options: ["Bandung", "Cairo", "Belgrade", "New Delhi"],
    answer: 2,
    explain: "Belgrade 1961. Trap: Bandung (1955) was the Afro-Asian Conference.",
  },
  {
    id: "fp3", paper: 2, unit: "India's Foreign Policy", format: "Direct",
    question: "The core principle of the Gujral Doctrine is:",
    options: ["Strategic autonomy", "Non-reciprocity towards smaller neighbours", "Nuclear no-first-use", "Look East engagement"],
    answer: 1,
    explain: "India gives to smaller neighbours in good faith without asking for reciprocity.",
  },
  {
    id: "fp4", paper: 2, unit: "India's Foreign Policy", format: "Chronology",
    source: { kind: "topic", label: "June 2026 paper: India–China chronology", url: "https://www.pw.live/ugc-net/exams/ugc-net-june-2026-political-science-question-paper" },
    question: "Arrange India–China events: A. Galwan clash  B. Panchsheel Agreement  C. Rajiv Gandhi's Beijing visit  D. Doklam standoff",
    options: ["B, C, D, A", "C, B, D, A", "B, D, C, A", "B, C, A, D"],
    answer: 0,
    explain: "1954 → 1988 → 2017 → 2020. An India–China chronology was asked in June 2026.",
  },
  {
    id: "fp5", paper: 2, unit: "India's Foreign Policy", format: "Direct",
    question: "The Simla Agreement (1972) was signed between India and:",
    options: ["China", "Pakistan", "Bangladesh", "Nepal"],
    answer: 1,
    explain: "Indira Gandhi and Z.A. Bhutto signed it after the 1971 war.",
  },
  {
    id: "fp6", paper: 2, unit: "India's Foreign Policy", format: "Direct",
    question: "MAHASAGAR, the upgraded version of SAGAR, was announced by India in 2025 during a visit to:",
    options: ["Sri Lanka", "Maldives", "Mauritius", "Seychelles"],
    answer: 2,
    explain: "It was announced in Mauritius in March 2025. SAGAR itself was launched in Mauritius in 2015.",
  },
  // Political Institutions
  {
    id: "pi1", paper: 2, unit: "Political Institutions", format: "Match",
    question:
      "Match: A. CAG  B. Finance Commission  C. Election Commission  D. Amendment procedure — I. Art. 324  II. Art. 368  III. Art. 148  IV. Art. 280",
    options: ["A-III, B-IV, C-I, D-II", "A-IV, B-III, C-I, D-II", "A-III, B-I, C-IV, D-II", "A-III, B-IV, C-II, D-I"],
    answer: 0,
    explain: "148, 280, 324, 368.",
  },
  {
    id: "pi2", paper: 2, unit: "Political Institutions", format: "Chronology",
    question: "Arrange: A. Minerva Mills  B. Golaknath  C. Kesavananda Bharati  D. Shankari Prasad",
    options: ["D, B, C, A", "B, D, C, A", "D, C, B, A", "D, B, A, C"],
    answer: 0,
    explain: "1951 → 1967 → 1973 → 1980.",
  },
  {
    id: "pi3", paper: 2, unit: "Political Institutions", format: "Direct",
    question: "Which state is NOT covered by the Sixth Schedule?",
    options: ["Assam", "Mizoram", "Manipur", "Tripura"],
    answer: 2,
    explain: "The Sixth Schedule covers Assam, Meghalaya, Tripura and Mizoram. Manipur is the classic trap.",
  },
  {
    id: "pi4", paper: 2, unit: "Political Institutions", format: "Statements",
    question:
      "About the 73rd Amendment: A. It added Part IX. B. It added the Eleventh Schedule with 29 subjects. C. It added the Twelfth Schedule. D. It provides one-third reservation for women.",
    options: ["A, B and D only", "A, C and D only", "B and C only", "A, B, C and D"],
    answer: 0,
    explain: "The Twelfth Schedule (18 subjects) and Part IXA come from the 74th Amendment.",
  },
  {
    id: "pi5", paper: 2, unit: "Political Institutions", format: "Chronology",
    source: { kind: "topic", label: "June 2025 paper: High Courts chronology", url: "https://prepp.in/paper/ugc-net-paper-2-political-science-26-jun-2025-shift-2-689bc7654f7583e6577d11ed" },
    question: "Arrange High Courts by establishment: A. Kerala  B. Karnataka (Mysore)  C. Sikkim  D. Guwahati",
    options: ["B, D, A, C", "D, B, A, C", "B, A, D, C", "B, D, C, A"],
    answer: 0,
    explain: "1884 → 1948 → 1956 → 1975. This type was asked in June 2025.",
  },
  {
    id: "pi6", paper: 2, unit: "Political Institutions", format: "Assertion-Reason",
    question:
      "A: Allocation of Lok Sabha seats among states is still based on the 1971 census. R: The 84th Amendment (2001) extended the freeze until the first census after 2026.",
    options: ["Both true, R explains A", "Both true, R does not explain A", "A true, R false", "A false, R true"],
    answer: 0,
    explain: "The 42nd Amendment froze allocation until the 2001 census, and the 84th extended it.",
  },
  {
    id: "pi7", paper: 2, unit: "Political Institutions", format: "Direct",
    question: "The anti-defection law (Tenth Schedule) was added by the:",
    options: ["42nd Amendment", "44th Amendment", "52nd Amendment", "61st Amendment"],
    answer: 2,
    explain: "52nd Amendment, 1985. The 91st (2003) removed the 'split' exception.",
  },
  {
    id: "pi8", paper: 2, unit: "Political Institutions", format: "Direct",
    question: "Which case held that the Preamble is part of the Constitution?",
    options: ["Berubari Union (1960)", "Kesavananda Bharati (1973)", "Minerva Mills (1980)", "S.R. Bommai (1994)"],
    answer: 1,
    explain: "Kesavananda overruled Berubari on this point.",
  },
  // Political Processes
  {
    id: "pp1", paper: 2, unit: "Political Processes", format: "Direct",
    source: { kind: "pyq", label: "PYQ (Testbook): 'Congress System' coined by", url: "https://testbook.com/question-answer/the-term-congress-system-was-coined-by--5f5a1cb1e9679ed48bfb9b37" },
    question: "The term 'Congress System' was coined by:",
    options: ["W.H. Morris-Jones", "Rajni Kothari", "Myron Weiner", "Paul Brass"],
    answer: 1,
    explain: "Rajni Kothari (1964). Morris-Jones described the 'three idioms' of Indian politics.",
  },
  {
    id: "pp2", paper: 2, unit: "Political Processes", format: "Direct",
    question: "The concepts 'Sanskritisation' and 'dominant caste' were given by:",
    options: ["G.S. Ghurye", "M.N. Srinivas", "André Béteille", "Louis Dumont"],
    answer: 1,
    explain: "M.N. Srinivas. Dumont wrote Homo Hierarchicus.",
  },
  {
    id: "pp3", paper: 2, unit: "Political Processes", format: "Chronology",
    question: "Arrange electoral reform committees: A. Indrajit Gupta  B. Tarkunde  C. Dinesh Goswami",
    options: ["B, C, A", "C, B, A", "B, A, C", "A, B, C"],
    answer: 0,
    explain: "1975 → 1990 → 1998.",
  },
  {
    id: "pp4", paper: 2, unit: "Political Processes", format: "Direct",
    question: "The Chipko Movement began in 1973 in present-day:",
    options: ["Himachal Pradesh", "Uttarakhand", "Karnataka", "Madhya Pradesh"],
    answer: 1,
    explain: "Chamoli district, then in Uttar Pradesh. Appiko was its Karnataka counterpart.",
  },
  {
    id: "pp5", paper: 2, unit: "Political Processes", format: "Direct",
    question: "State of Punjab v. Davinder Singh (2024) is significant for:",
    options: ["Electoral bonds", "Sub-classification of Scheduled Castes", "Governor's assent", "Right to privacy"],
    answer: 1,
    explain: "It allowed sub-classification of SCs and overruled E.V. Chinnaiah (2004).",
  },
  // Public Administration
  {
    id: "pa1", paper: 2, unit: "Public Administration", format: "Direct",
    source: { kind: "topic", label: "Dec 2023 paper: Acceptance Theory", url: "https://www.shiksha.com/sarkari-exams/teaching/articles/ugc-net-2023-exam-analysis-political-science-blogId-146139" },
    question: "The 'acceptance theory of authority' was given by:",
    options: ["Henri Fayol", "Chester Barnard", "Mary Parker Follett", "Max Weber"],
    answer: 1,
    explain: "Barnard, The Functions of the Executive (1938). This was asked in Dec 2023.",
  },
  {
    id: "pa2", paper: 2, unit: "Public Administration", format: "Chronology",
    source: { kind: "pyq", label: "June 2025 paper: Likert Systems 1–4", url: "https://prepp.in/paper/ugc-net-paper-2-political-science-26-jun-2025-shift-2-689bc7654f7583e6577d11ed" },
    question: "Arrange Likert's management systems from System 1 to System 4: A. Consultative  B. Exploitative-authoritative  C. Participative  D. Benevolent-authoritative",
    options: ["B, D, A, C", "D, B, A, C", "B, A, D, C", "B, D, C, A"],
    answer: 0,
    explain: "Likert's System 4 (participative) is the ideal. This was asked in June 2025.",
  },
  {
    id: "pa3", paper: 2, unit: "Public Administration", format: "Match",
    question:
      "Match: A. Fred Riggs  B. Herbert Simon  C. Charles Lindblom  D. Yehezkel Dror — I. Muddling through  II. Normative-optimum model  III. Prismatic-sala  IV. Bounded rationality",
    options: ["A-III, B-IV, C-I, D-II", "A-IV, B-III, C-I, D-II", "A-III, B-I, C-IV, D-II", "A-III, B-IV, C-II, D-I"],
    answer: 0,
    explain: "Riggs, Simon (Administrative Behavior), Lindblom (1959), Dror.",
  },
  {
    id: "pa4", paper: 2, unit: "Public Administration", format: "Direct",
    question: "The acronym POSDCORB was coined by:",
    options: ["Henri Fayol", "Luther Gulick", "L. Urwick", "W.F. Willoughby"],
    answer: 1,
    explain: "Gulick (1937, with Urwick as co-editor of the Papers). Trap: Fayol gave POCCC.",
  },
  {
    id: "pa5", paper: 2, unit: "Public Administration", format: "Chronology",
    question: "Arrange: A. New Public Management (Hood)  B. Minnowbrook I  C. Reinventing Government  D. Comparative Administration Group",
    options: ["D, B, A, C", "B, D, A, C", "D, B, C, A", "D, A, B, C"],
    answer: 0,
    explain: "CAG 1960 → Minnowbrook 1968 → Hood 1991 → Osborne & Gaebler 1992.",
  },
  {
    id: "pa6", paper: 2, unit: "Public Administration", format: "Direct",
    question: "'New Public Service' as an alternative to NPM was proposed by:",
    options: ["Osborne & Gaebler", "Denhardt & Denhardt", "Christopher Hood", "Dwight Waldo"],
    answer: 1,
    explain: "Its core idea is 'serve, rather than steer' (2000).",
  },
  {
    id: "pa7", paper: 2, unit: "Public Administration", format: "Direct",
    question: "Which is NOT among Fayol's 14 principles of management?",
    options: ["Unity of command", "Scalar chain", "Esprit de corps", "Control"],
    answer: 3,
    explain: "Control is one of Fayol's 5 FUNCTIONS (POCCC), not one of the 14 principles.",
  },
  {
    id: "pa8", paper: 2, unit: "Public Administration", format: "Direct",
    question: "The 'Hawthorne experiments' are associated with:",
    options: ["F.W. Taylor", "Elton Mayo", "Abraham Maslow", "Douglas McGregor"],
    answer: 1,
    explain: "Human Relations school (1924–32).",
  },
  // Governance & Public Policy
  {
    id: "gp1", paper: 2, unit: "Governance & Policy", format: "Direct",
    question: "The Second Administrative Reforms Commission (2005) was first chaired by:",
    options: ["Morarji Desai", "Veerappa Moily", "K. Hanumanthaiya", "B.N. Srikrishna"],
    answer: 1,
    explain: "Moily chaired the 2nd ARC. The 1st ARC (1966) was chaired by Desai, then Hanumanthaiya.",
  },
  {
    id: "gp2", paper: 2, unit: "Governance & Policy", format: "Chronology",
    question: "Arrange: A. Lokpal and Lokayuktas Act  B. RTI Act  C. DPDP Act  D. MGNREGA",
    options: ["B, D, A, C", "D, B, A, C", "B, A, D, C", "B, D, C, A"],
    answer: 0,
    explain: "RTI (June 2005) → MGNREGA (Sept 2005) → Lokpal 2013 → DPDP 2023.",
  },
  {
    id: "gp3", paper: 2, unit: "Governance & Policy", format: "Direct",
    question: "The GST Council is provided for under:",
    options: ["Article 263", "Article 279A", "Article 280", "Article 246A"],
    answer: 1,
    explain: "279A (101st Amendment). 246A covers the power to make GST laws, and 263 is the Inter-State Council.",
  },
  {
    id: "gp4", paper: 2, unit: "Governance & Policy", format: "Direct",
    question: "The DPDP Act, 2023 amended which provision of the RTI Act?",
    options: ["Section 4(1)(b)", "Section 6", "Section 8(1)(j)", "Section 24"],
    answer: 2,
    explain: "8(1)(j), the personal-information exemption. The amendment removed its public-interest override.",
  },
  // Past-paper confirmed additions: each carries the page where the question or topic was found.
  {
    id: "y1", paper: 2, unit: "India's Foreign Policy", format: "Chronology",
    source: { kind: "pyq", label: "PYQ (Adda247): treaties chronology", url: "https://www.adda247.com/question-answer/arrange-the-following-treaties-and-agreements-in-the-chronological-order-a-india-and-bangladesh-signed-the-farakka-treaty-for-sharing-of-the-ganga/q.v1.6d874ed7-40ea-43a6-abda-c438f42c77e7-en" },
    question:
      "Arrange chronologically: A. India–Bangladesh Farakka Treaty on Ganga waters  B. Shimla Agreement  C. Indus Waters Treaty  D. Vajpayee's Lahore bus journey and declaration  E. Tashkent Agreement",
    options: ["C, E, B, A, D", "E, C, B, A, D", "C, B, E, A, D", "C, E, A, B, D"],
    answer: 0,
    explain: "1960 → 1966 → 1972 → 1977 → 1999.",
  },
  {
    id: "y2", paper: 2, unit: "International Relations", format: "Direct",
    source: { kind: "pyq", label: "Jan 2026 paper (memory-based)", url: "https://www.adda247.com/jobs/wp-content/uploads/sites/13/2026/01/07180604/MEMORY-BASED-QUESTIONS-OF-UGC-NET-Political-Science-06-JAN-2026-SHIFT-1.pdf" },
    question: "In 2017, which country's Prime Minister abruptly announced his resignation while in Saudi Arabia on 4 November?",
    options: ["Lebanon", "Jordan", "Iraq", "Yemen"],
    answer: 0,
    explain: "Saad Hariri of Lebanon, who later withdrew the resignation. 'Current affairs' in NET can be 8+ years old.",
  },
  {
    id: "y3", paper: 2, unit: "Indian Thought", format: "Direct",
    source: { kind: "pyq", label: "PYQ (Testbook): Hind Swaraj", url: "https://testbook.com/question-answer/hind-swaraj-was-written-by-gandhi-whil--6092a27d61f2400fa1713519" },
    question: "'Hind Swaraj' was written by Gandhi while:",
    options: [
      "Imprisoned in Yerwada jail",
      "Sailing from London to South Africa",
      "Staying at Sabarmati Ashram",
      "Living at Tolstoy Farm",
    ],
    answer: 1,
    explain: "Written in 1909 aboard the SS Kildonan Castle. It takes the form of a dialogue between 'the Reader' and 'the Editor'.",
  },
  {
    id: "y4", paper: 2, unit: "Western Thought", format: "Chronology",
    source: { kind: "pyq", label: "PYQ (Testbook): Arendt's works in order", url: "https://testbook.com/question-answer/arrange-the-work-of-hannah-arendt-in-ascending-ord--62c2ad08e6b4d51236d9cc87" },
    question: "Arrange the works of Hannah Arendt in ascending order: A. On Revolution  B. The Human Condition  C. The Origins of Totalitarianism  D. On Violence",
    options: ["C, B, A, D", "B, C, A, D", "C, A, B, D", "C, B, D, A"],
    answer: 0,
    explain: "1951 → 1958 → 1963 → 1970.",
  },
  {
    id: "y5", paper: 2, unit: "Indian Thought", format: "Chronology",
    source: { kind: "pyq", label: "PYQ (Testbook): Ambedkar's writings in order", url: "https://testbook.com/question-answer/arrange-the-writings-of-dr-b-r-ambedkar-in-a-ch--64ac0978c0ea2bd550163e49" },
    question: "Arrange Ambedkar's writings chronologically: A. Who Were the Shudras?  B. Castes in India  C. States and Minorities  D. Annihilation of Caste",
    options: ["B, D, A, C", "D, B, A, C", "B, A, D, C", "B, D, C, A"],
    answer: 0,
    explain: "Castes in India 1916 → Annihilation of Caste 1936 → Who Were the Shudras? 1946 → States and Minorities 1947.",
  },
  {
    id: "y6", paper: 2, unit: "Political Theory", format: "Direct",
    source: { kind: "pyq", label: "PYQ (Testbook): cosmopolitan democracy", url: "https://testbook.com/question-answer/who-among-the-following-thinkers-is-an-advocate-of--64ac0869a36c25f49f97da8b" },
    question: "Who among the following thinkers is an advocate of cosmopolitan democracy?",
    options: ["Immanuel Kant", "Thomas Hobbes", "Niccolò Machiavelli", "Carl Schmitt"],
    answer: 0,
    explain: "Kant's Perpetual Peace (1795) argued for cosmopolitan right and a federation of free states. David Held developed the modern theory.",
  },
  {
    id: "y7", paper: 2, unit: "Western Thought", format: "Direct",
    source: { kind: "pyq", label: "PYQ (Testbook question bank)", url: "https://testbook.com/questions/ugc-net-political-science-questions--647075e4203c62355f5d326b" },
    question: "Who described the general inclination of mankind as 'a perpetual and restless desire of power after power, that ceaseth only in death'?",
    options: ["Machiavelli", "Thomas Hobbes", "Friedrich Nietzsche", "John Locke"],
    answer: 1,
    explain: "Hobbes, Leviathan (1651), Chapter 11.",
  },
  {
    id: "y8", paper: 2, unit: "Political Theory", format: "Direct",
    source: { kind: "pyq", label: "PYQ (Testbook question bank)", url: "https://testbook.com/questions/ugc-net-political-science-questions--647075e4203c62355f5d326b" },
    question: "Who said that political theory contains factors of three kinds: the factual, the causal and the valuational?",
    options: ["David Easton", "G.H. Sabine", "Harold Laski", "Robert Dahl"],
    answer: 1,
    explain: "George H. Sabine (A History of Political Theory).",
  },
  {
    id: "y9", paper: 2, unit: "Public Administration", format: "Direct",
    source: { kind: "pyq", label: "PYQ (Dec 2012 Paper II)", url: "https://www.netugc.com/ugc-net-solved-question-papers-in-political-science/2012-december-ugc-net-solved-question-paper-in-political-science-paper-2" },
    question: "'Clect' is a sub-system of Riggs' prismatic society. It belongs to the:",
    options: ["Social system", "Administrative system", "Economic system", "Political system"],
    answer: 0,
    explain: "In Riggs' prismatic model, clects are the social structure, the bazaar-canteen is the economic one, and the sala is the administrative one.",
  },
  {
    id: "y10", paper: 2, unit: "Comparative Politics", format: "Direct",
    source: { kind: "pyq", label: "PYQ (Testbook): Pye's crises", url: "https://testbook.com/question-answer/lucian-pye-had-identified-crises-that-ne--626e4de7a7b1268c650a3a6b" },
    question: "Which of the following is NOT among the crises of political development identified by Lucian Pye?",
    options: ["Identity", "Penetration", "Secularisation", "Distribution"],
    answer: 2,
    explain: "Pye's six crises are identity, legitimacy, penetration, participation, integration and distribution.",
  },
  {
    id: "y11", paper: 2, unit: "Comparative Politics", format: "Direct",
    source: { kind: "pyq", label: "PYQ (Testbook): components of political culture", url: "https://testbook.com/question-answer/the-concept-of-political-culture-involves-three-co--63b97fff92f76a7d687d8dd9" },
    question: "The concept of political culture (Almond & Powell) involves three components of orientation. They are:",
    options: [
      "Cognitive, affective, evaluative",
      "Cognitive, normative, behavioural",
      "Affective, legal, institutional",
      "Parochial, subject, participant",
    ],
    answer: 0,
    explain: "Trap: parochial, subject and participant are TYPES of political culture, not components of orientation.",
  },
  {
    id: "y12", paper: 2, unit: "International Relations", format: "Direct",
    source: { kind: "pyq", label: "PYQ (Testbook): Kenneth Waltz", url: "https://testbook.com/question-answer/kenneth-waltz-was-a--63b92a7a9f31f10fe4aabacd" },
    question: "Kenneth Waltz was a:",
    options: ["Classical realist", "Neo-realist", "Neo-liberal institutionalist", "Constructivist"],
    answer: 1,
    explain: "Theory of International Politics (1979) is structural realism.",
  },
  {
    id: "y13", paper: 2, unit: "International Relations", format: "Statements",
    source: { kind: "pyq", label: "PYQ (Testbook): Morgenthau's principles", url: "https://testbook.com/question-answer/morgenthaus-principles-of-political-realism-a--689c87ee77caa7d5672c37e3" },
    question:
      "Which are among Morgenthau's principles of political realism? A. Politics is governed by objective laws rooted in human nature. B. Interest is defined in terms of power. C. Universal moral principles apply to state action in their abstract, universal form. D. The political sphere is autonomous.",
    options: ["A, B and D only", "A, B and C only", "B, C and D only", "A, B, C and D"],
    answer: 0,
    explain: "C is the reverse of what Morgenthau says: moral principles must be 'filtered through circumstances of time and place'.",
  },
  {
    id: "y14", paper: 2, unit: "India's Foreign Policy", format: "Direct",
    source: { kind: "pyq", label: "PYQ (Testbook): India, NPT and CTBT", url: "https://testbook.com/question-answer/which-of-the-following-statements-is-true-with-reg--6274273ca4e93f69e815337e" },
    question: "Which statement is true regarding India and the NPT and CTBT?",
    options: [
      "India signed the NPT but not the CTBT",
      "India signed the CTBT but not the NPT",
      "India has signed both",
      "India has signed neither",
    ],
    answer: 3,
    explain: "India calls both discriminatory. It opposed the NPT's indefinite extension in 1995 and refused the CTBT in 1996.",
  },
  {
    id: "y15", paper: 2, unit: "Political Institutions", format: "Direct",
    source: { kind: "pyq", label: "PYQ (Testbook): Union Constitution Committee", url: "https://testbook.com/question-answer/who-was-the-chairman-of-the-union-constitution-com--63adb3c8355635c43ff3e791" },
    question: "Who was the Chairman of the Union Constitution Committee of the Constituent Assembly?",
    options: ["Sardar Patel", "Jawaharlal Nehru", "Rajendra Prasad", "B.R. Ambedkar"],
    answer: 1,
    explain: "Nehru chaired the Union Constitution and Union Powers committees. Patel chaired Fundamental Rights & Minorities and the Provincial Constitution committee.",
  },
  {
    id: "y16", paper: 2, unit: "Political Institutions", format: "Direct",
    source: { kind: "pyq", label: "PYQ (Testbook): Steering Committee", url: "https://testbook.com/question-answer/the-chairman-of-the-steering-committee-in-the-cons--6981c610e7ab8c4ecc6d1679" },
    question: "The chairman of the Steering Committee in the Constituent Assembly was:",
    options: ["Rajendra Prasad", "Jawaharlal Nehru", "B.R. Ambedkar", "K.M. Munshi"],
    answer: 0,
    explain: "Rajendra Prasad chaired the Assembly and the Steering Committee. The Drafting Committee (29 Aug 1947) was chaired by Ambedkar.",
  },
  {
    id: "y17", paper: 2, unit: "Western Thought", format: "Direct",
    source: { kind: "topic", label: "PYQ topic (Testbook): Arendt", url: "https://testbook.com/question-answer/which-of-the-following-are-correcta-hannah-are--63b97f085486737c83db06d1" },
    question: "The phrase 'banality of evil' is associated with:",
    options: ["Theodor Adorno", "Hannah Arendt", "Herbert Marcuse", "Jürgen Habermas"],
    answer: 1,
    explain: "Arendt, Eichmann in Jerusalem (1963).",
  },
  {
    id: "y18", paper: 2, unit: "International Relations", format: "Chronology",
    source: { kind: "topic", label: "Dec 2024 cycle: Axis alliance formation", url: "https://www.oliveboard.in/blog/ugc-net-political-science-exam-analysis-2024-6-jan-2025/" },
    question: "Arrange: A. Tripartite Pact  B. Anti-Comintern Pact  C. Pact of Steel",
    options: ["B, C, A", "C, B, A", "B, A, C", "A, B, C"],
    answer: 0,
    explain: "Anti-Comintern 1936 (Germany–Japan) → Pact of Steel 1939 (Germany–Italy) → Tripartite 1940 (Germany–Italy–Japan).",
  },
  {
    id: "y19", paper: 2, unit: "Political Theory", format: "Direct",
    source: { kind: "topic", label: "Dec 2024 cycle: origins of ecofeminism", url: "https://www.oliveboard.in/blog/ugc-net-political-science-exam-analysis-2024-6-jan-2025/" },
    question: "The term 'ecofeminism' was coined by:",
    options: ["Vandana Shiva", "Françoise d'Eaubonne", "Maria Mies", "Carolyn Merchant"],
    answer: 1,
    explain: "d'Eaubonne (1974). Shiva and Mies co-wrote Ecofeminism (1993), and Merchant wrote The Death of Nature.",
  },
  {
    id: "y20", paper: 2, unit: "India's Foreign Policy", format: "Match",
    source: { kind: "topic", label: "Dec 2023 paper: military exercises", url: "https://www.shiksha.com/sarkari-exams/teaching/articles/ugc-net-2023-exam-analysis-political-science-blogId-146139" },
    question:
      "Match exercise with partner: A. Yudh Abhyas  B. Mitra Shakti  C. Nomadic Elephant  D. Dharma Guardian — I. Japan  II. Mongolia  III. Sri Lanka  IV. USA",
    options: ["A-IV, B-III, C-II, D-I", "A-III, B-IV, C-II, D-I", "A-IV, B-II, C-III, D-I", "A-IV, B-III, C-I, D-II"],
    answer: 0,
    explain: "All four are army exercises with India.",
  },
];

export const paper1Bank: MCQ[] = [
  {
    id: "t1", paper: 1, unit: "Teaching Aptitude", format: "Direct",
    question: "Evaluation carried out during instruction to improve learning is:",
    options: ["Summative", "Formative", "Placement", "Norm-referenced"],
    answer: 1,
    explain: "Formative is during instruction and summative is at the end.",
  },
  {
    id: "t2", paper: 1, unit: "Teaching Aptitude", format: "Chronology",
    question: "Arrange levels of revised Bloom's taxonomy from lowest: A. Evaluate  B. Apply  C. Create  D. Understand",
    options: ["D, B, A, C", "B, D, A, C", "D, B, C, A", "D, A, B, C"],
    answer: 0,
    explain: "Remember → Understand → Apply → Analyse → Evaluate → Create.",
  },
  {
    id: "t3", paper: 1, unit: "Teaching Aptitude", format: "Direct",
    question: "'Withitness' in classroom management was described by:",
    options: ["Jacob Kounin", "Donald Schön", "B.F. Skinner", "Jerome Bruner"],
    answer: 0,
    explain: "Kounin. Schön: the reflective practitioner.",
  },
  {
    id: "t4", paper: 1, unit: "Teaching Aptitude", format: "Direct",
    question: "Which is NOT one of the four pillars in the Delors Report?",
    options: ["Learning to know", "Learning to do", "Learning to earn", "Learning to be"],
    answer: 2,
    explain: "The fourth pillar is Learning to live together.",
  },
  {
    id: "r1", paper: 1, unit: "Research Aptitude", format: "Direct",
    question: "A weighing machine shows the same wrong weight every time. It is:",
    options: ["Valid and reliable", "Reliable but not valid", "Valid but not reliable", "Neither"],
    answer: 1,
    explain: "It is consistent, so reliable. It is inaccurate, so not valid.",
  },
  {
    id: "r2", paper: 1, unit: "Research Aptitude", format: "Direct",
    question: "Population divided into male and female groups, and a random sample taken from EACH group, is:",
    options: ["Cluster sampling", "Stratified sampling", "Quota sampling", "Systematic sampling"],
    answer: 1,
    explain: "Every group is sampled, so it is stratified. Cluster sampling picks some whole groups.",
  },
  {
    id: "r3", paper: 1, unit: "Research Aptitude", format: "Direct",
    question: "Rejecting a true null hypothesis is a:",
    options: ["Type I error", "Type II error", "Sampling error", "Standard error"],
    answer: 0,
    explain: "Type I rejects a true H0. Type II fails to reject a false H0.",
  },
  {
    id: "r4", paper: 1, unit: "Research Ethics", format: "Direct",
    question: "Which is NOT part of 'FFP' research misconduct?",
    options: ["Fabrication", "Falsification", "Plagiarism", "Duplicate publication"],
    answer: 3,
    explain: "Duplicate publication is a questionable practice, but FFP is only Fabrication, Falsification and Plagiarism.",
  },
  {
    id: "l1", paper: 1, unit: "Logical Reasoning", format: "Direct",
    question: "The contradictory of 'All S are P' is:",
    options: ["No S are P", "Some S are P", "Some S are not P", "All P are S"],
    answer: 2,
    explain: "A and O are contradictory. A and E are contrary.",
  },
  {
    id: "l2", paper: 1, unit: "Logical Reasoning", format: "Direct",
    question: "'Don't accept his tax argument, he failed economics' commits:",
    options: ["Straw man", "Ad hominem", "Red herring", "Slippery slope"],
    answer: 1,
    explain: "It attacks the person, not the argument.",
  },
  {
    id: "l3", paper: 1, unit: "Logical Reasoning", format: "Direct",
    source: { kind: "topic", label: "PYQ topic (Testbook): Nyaya philosophy", url: "https://testbook.com/question-answer/with-reference-to-ny%C4%81ya-philosophy-which-of-the--62c044e15875c69172d54383" },
    question: "How many pramanas (means of valid knowledge) does Nyaya accept?",
    options: ["2", "3", "4", "6"],
    answer: 2,
    explain: "Pratyaksha, Anumana, Upamana, Shabda. Charvaka accepts 1 and Bhatta Mimamsa and Vedanta accept 6.",
  },
  {
    id: "l4", paper: 1, unit: "Logical Reasoning", format: "Direct",
    question: "In Indian logic, 'Hetvabhasa' means:",
    options: ["Valid inference", "Fallacy of the middle term (reason)", "Verbal testimony", "Comparison"],
    answer: 1,
    explain: "It means a fallacious reason (hetu), like a fallacy in the middle term.",
  },
  {
    id: "l5", paper: 1, unit: "Logical Reasoning", format: "Direct",
    question: "Which proposition can be validly converted only 'by limitation'?",
    options: ["A", "E", "I", "O"],
    answer: 0,
    explain: "'All S are P' becomes 'Some P are S'. E and I convert simply. O does not convert.",
  },
  {
    id: "m1", paper: 1, unit: "Mathematical Reasoning", format: "Direct",
    question: "The average of 5 numbers is 20. A sixth number, 32, is added. The new average is:",
    options: ["21", "22", "24", "26"],
    answer: 1,
    explain: "Total 100 + 32 = 132. 132 ÷ 6 = 22.",
  },
  {
    id: "m2", paper: 1, unit: "Mathematical Reasoning", format: "Direct",
    question: "A value rises from 80 to 100. The percentage increase is:",
    options: ["20%", "25%", "80%", "125%"],
    answer: 1,
    explain: "(100 − 80) ÷ 80 × 100 = 25%. Divide by the OLD value.",
  },
  {
    id: "m3", paper: 1, unit: "Mathematical Reasoning", format: "Direct",
    question: "₹500 divided in the ratio 2:3. The larger share is:",
    options: ["₹200", "₹250", "₹300", "₹350"],
    answer: 2,
    explain: "5 parts make 500, so one part is 100. 3 parts = 300.",
  },
  {
    id: "m4", paper: 1, unit: "Mathematical Reasoning", format: "Direct",
    question: "Next term: 2, 6, 12, 20, 30, ?",
    options: ["40", "42", "44", "36"],
    answer: 1,
    explain: "The differences are +4, +6, +8, +10, +12, so the next term is 42 (n × (n+1)).",
  },
  {
    id: "c1", paper: 1, unit: "ICT", format: "Direct",
    question: "The binary equivalent of decimal 10 is:",
    options: ["1001", "1010", "1100", "1110"],
    answer: 1,
    explain: "8 + 2 = 10, which is 1010.",
  },
  {
    id: "c2", paper: 1, unit: "ICT", format: "Direct",
    question: "In e-mail, which field hides recipients from each other?",
    options: ["To", "CC", "BCC", "Subject"],
    answer: 2,
    explain: "BCC stands for Blind Carbon Copy.",
  },
  {
    id: "c3", paper: 1, unit: "ICT", format: "Direct",
    question: "Who is known as the 'Father of the Computer'?",
    options: ["Alan Turing", "Charles Babbage", "John von Neumann", "Tim Berners-Lee"],
    answer: 1,
    explain: "Babbage, for the Analytical Engine. Turing is the father of theoretical computer science and AI.",
  },
  {
    id: "e1", paper: 1, unit: "Environment", format: "Direct",
    question: "The Montreal Protocol (1987) deals with:",
    options: ["Greenhouse gas reduction", "Ozone-depleting substances", "Hazardous waste trade", "Biodiversity"],
    answer: 1,
    explain: "Kyoto covers GHGs, Basel covers hazardous waste and the CBD covers biodiversity.",
  },
  {
    id: "e2", paper: 1, unit: "Environment", format: "Direct",
    question: "India's net-zero emissions target year (Panchamrit, COP26) is:",
    options: ["2047", "2050", "2060", "2070"],
    answer: 3,
    explain: "2070, announced at COP26 in Glasgow in 2021.",
  },
  {
    id: "h1", paper: 1, unit: "Higher Education", format: "Chronology",
    question: "Arrange: A. Kothari Commission  B. Radhakrishnan Commission  C. UGC Act  D. National Policy on Education",
    options: ["B, C, A, D", "C, B, A, D", "B, A, C, D", "B, C, D, A"],
    answer: 0,
    explain: "1948–49 → 1956 → 1964–66 → 1986.",
  },
  {
    id: "h2", paper: 1, unit: "Higher Education", format: "Direct",
    question: "NAAC is headquartered at:",
    options: ["New Delhi", "Bengaluru", "Hyderabad", "Pune"],
    answer: 1,
    explain: "Bengaluru, established in 1994.",
  },
  {
    id: "h3", paper: 1, unit: "Higher Education", format: "Direct",
    question: "Under NEP 2020, the target Gross Enrolment Ratio in higher education by 2035 is:",
    options: ["35%", "40%", "50%", "60%"],
    answer: 2,
    explain: "50% by 2035.",
  },
  {
    id: "y21", paper: 1, unit: "Logical Reasoning", format: "Chronology",
    source: { kind: "topic", label: "PYQ topic (Testbook): Nyaya syllogism", url: "https://testbook.com/question-answer/with-reference-to-ny%C4%81ya-philosophy-which-of-the--62c044e15875c69172d54383" },
    question: "Arrange the five members of the Nyaya syllogism in order: A. Upanaya  B. Pratijna  C. Nigamana  D. Hetu  E. Udaharana",
    options: ["B, D, E, A, C", "D, B, E, A, C", "B, E, D, A, C", "B, D, A, E, C"],
    answer: 0,
    explain: "Proposition → Reason → Example → Application → Conclusion.",
  },
];
